return {
PlaceObj('ModItemCode', {
	'name', "CraftOperationsRecipeDef",
	'CodeFileName', "Code/CraftOperationsRecipeDef.lua",
}),
PlaceObj('ModItemCode', {
	'name', "RecipeDef",
	'CodeFileName', "Code/RecipeDef.lua",
}),
PlaceObj('ModItemInventoryItemCompositeDef', {
	'Group', "Upgrade",
	'Id', "crate_bereta92f",
	'object_class', "MiscItem",
	'Repairable', false,
	'Icon', "Mod/Dwo4JJm/icons/cratesmall.png",
	'SubIcon', "UI/Icons/Weapons/Beretta92F",
	'DisplayName', T(704101335198, --[[ModItemInventoryItemCompositeDef crate_bereta92f DisplayName]] "HG - Berettas in a Crate"),
	'DisplayNamePlural', T(782905059151, --[[ModItemInventoryItemCompositeDef crate_bereta92f DisplayNamePlural]] "HG - Berettas in Crates"),
	'Description', T(327416655297, --[[ModItemInventoryItemCompositeDef crate_bereta92f Description]] "A couple of Berettas in an old recycled army crate."),
	'AdditionalHint', T(484844574916, --[[ModItemInventoryItemCompositeDef crate_bereta92f AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Some assembly required."),
}),
PlaceObj('ModItemInventoryItemCompositeDef', {
	'Group', "Upgrade",
	'Id', "crate_Microchip",
	'object_class', "MiscItem",
	'Repairable', false,
	'Icon', "Mod/Dwo4JJm/icons/cratesmall.png",
	'SubIcon', "UI/Icons/Items/microchip",
	'DisplayName', T(716101335198, --[[ModItemInventoryItemCompositeDef crate_Microchip DisplayName]] "PARTS - Microchip Crate"),
	'DisplayNamePlural', T(716905059151, --[[ModItemInventoryItemCompositeDef crate_Microchip DisplayNamePlural]] "PARTS - Microchip Crates"),
	'Description', T(716416655297, --[[ModItemInventoryItemCompositeDef crate_Microchip Description]] "A crate of 10 generic chips. Use these for crafting."),
	'AdditionalHint', T(716844574916, --[[ModItemInventoryItemCompositeDef crate_Microchip AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Some assembly required."),
}),
PlaceObj('ModItemInventoryItemCompositeDef', {
	'Group', "Upgrade",
	'Id', "crate_peacemaker",
	'object_class', "MiscItem",
	'Repairable', false,
	'Icon', "Mod/Dwo4JJm/icons/cratesmall.png",
	'SubIcon', "UI/Icons/Weapons/Colt Peacemaker",
	'DisplayName', T(637733129688, --[[ModItemInventoryItemCompositeDef crate_peacemaker DisplayName]] "HG - Peacemakers in a Crate"),
	'DisplayNamePlural', T(401571844725, --[[ModItemInventoryItemCompositeDef crate_peacemaker DisplayNamePlural]] "HG - Peacemakers in Crates"),
	'Description', T(725203777470, --[[ModItemInventoryItemCompositeDef crate_peacemaker Description]] "A couple of Peacemakers in a crate as old as the guns."),
	'AdditionalHint', T(322199667175, --[[ModItemInventoryItemCompositeDef crate_peacemaker AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Some assembly required."),
}),
PlaceObj('ModItemInventoryItemCompositeDef', {
	'Group', "Upgrade",
	'Id', "crate_coltanaconda",
	'object_class', "MiscItem",
	'Repairable', false,
	'Icon', "Mod/Dwo4JJm/icons/cratesmall.png",
	'SubIcon', "UI/Icons/Weapons/Anaconda",
	'DisplayName', T(524653239941, --[[ModItemInventoryItemCompositeDef crate_coltanaconda DisplayName]] "HG - Colt Anaconda in a Crate"),
	'DisplayNamePlural', T(564951160435, --[[ModItemInventoryItemCompositeDef crate_coltanaconda DisplayNamePlural]] "HG - Colt Anacondas in Crates"),
	'Description', T(962924203321, --[[ModItemInventoryItemCompositeDef crate_coltanaconda Description]] "A Colt Anaconda in an old recycled army crate. The gun must've gone off in transit, the crate has a hole the size of a baby in the side."),
	'AdditionalHint', T(314526251398, --[[ModItemInventoryItemCompositeDef crate_coltanaconda AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Some assembly required."),
}),
PlaceObj('ModItemInventoryItemCompositeDef', {
	'Group', "Upgrade",
	'Id', "crate_flaregun",
	'object_class', "MiscItem",
	'Repairable', false,
	'Icon', "Mod/Dwo4JJm/icons/cratesmall.png",
	'SubIcon', "UI/Icons/Weapons/FlareGun",
	'DisplayName', T(808451785897, --[[ModItemInventoryItemCompositeDef crate_flaregun DisplayName]] "HG - Flare Gun in a Crate"),
	'DisplayNamePlural', T(449796698396, --[[ModItemInventoryItemCompositeDef crate_flaregun DisplayNamePlural]] "HG - Flare Guns in Crates"),
	'Description', T(468012067994, --[[ModItemInventoryItemCompositeDef crate_flaregun Description]] "A flare gun with complimentary ammo in a soggy old navy crate."),
	'AdditionalHint', T(552601158130, --[[ModItemInventoryItemCompositeDef crate_flaregun AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Some assembly required."),
}),
PlaceObj('ModItemInventoryItemCompositeDef', {
	'Group', "Upgrade",
	'Id', "crate_deserteagle",
	'object_class', "MiscItem",
	'Repairable', false,
	'Icon', "Mod/Dwo4JJm/icons/cratesmall.png",
	'SubIcon', "UI/Icons/Weapons/DesertEagle",
	'DisplayName', T(584454564071, --[[ModItemInventoryItemCompositeDef crate_deserteagle DisplayName]] "HG - Desert Eagle in a Crate"),
	'DisplayNamePlural', T(166536867525, --[[ModItemInventoryItemCompositeDef crate_deserteagle DisplayNamePlural]] "HG - Desert Eagles in Crates"),
	'Description', T(838660191087, --[[ModItemInventoryItemCompositeDef crate_deserteagle Description]] "A Desert Eagle in an old recycled army crate. This big bastard popped all of the bubble wrap it was packed with."),
	'AdditionalHint', T(423365235321, --[[ModItemInventoryItemCompositeDef crate_deserteagle AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Some assembly required."),
}),
PlaceObj('ModItemInventoryItemCompositeDef', {
	'Group', "Upgrade",
	'Id', "crate_glock18",
	'object_class', "MiscItem",
	'Repairable', false,
	'Icon', "Mod/Dwo4JJm/icons/cratesmall.png",
	'SubIcon', "UI/Icons/Weapons/Glock18",
	'DisplayName', T(838120270415, --[[ModItemInventoryItemCompositeDef crate_glock18 DisplayName]] "HG - Glocks in a Crate"),
	'DisplayNamePlural', T(595140528923, --[[ModItemInventoryItemCompositeDef crate_glock18 DisplayNamePlural]] "HG - Glocks in Crates"),
	'Description', T(611369089926, --[[ModItemInventoryItemCompositeDef crate_glock18 Description]] "A couple of Glock 18s in an old recycled army crate."),
	'AdditionalHint', T(281438413666, --[[ModItemInventoryItemCompositeDef crate_glock18 AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Some assembly required."),
}),
PlaceObj('ModItemInventoryItemCompositeDef', {
	'Group', "Upgrade",
	'Id', "crate_Ak47",
	'object_class', "MiscItem",
	'Repairable', false,
	'Icon', "Mod/Dwo4JJm/icons/cratebig.png",
	'SubIcon', "UI/Icons/Weapons/AK47",
	'DisplayName', T(303230643712, --[[ModItemInventoryItemCompositeDef crate_Ak47 DisplayName]] "AR - AK-47 in a Crate"),
	'DisplayNamePlural', T(455958976569, --[[ModItemInventoryItemCompositeDef crate_Ak47 DisplayNamePlural]] "AR - AK-47s in Crates"),
	'Description', T(307441541885, --[[ModItemInventoryItemCompositeDef crate_Ak47 Description]] "An AK-47 in an army crate, but being honest the AK probably didn't need the crate."),
	'AdditionalHint', T(670811379780, --[[ModItemInventoryItemCompositeDef crate_Ak47 AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Some assembly required."),
	'LargeItem', true,
}),
PlaceObj('ModItemInventoryItemCompositeDef', {
	'Group', "Upgrade",
	'Id', "crate_AK74",
	'object_class', "MiscItem",
	'Repairable', false,
	'Icon', "Mod/Dwo4JJm/icons/cratebig.png",
	'SubIcon', "UI/Icons/Weapons/AK74",
	'DisplayName', T(814859765012, --[[ModItemInventoryItemCompositeDef crate_AK74 DisplayName]] "AR - AK-74 in a Crate"),
	'DisplayNamePlural', T(139241948019, --[[ModItemInventoryItemCompositeDef crate_AK74 DisplayNamePlural]] "AR - AK-74s in Crates"),
	'Description', T(644611569712, --[[ModItemInventoryItemCompositeDef crate_AK74 Description]] "An AK74 in a classic Soviet crate. Still has some Afghani sand in the cracks."),
	'AdditionalHint', T(670086747925, --[[ModItemInventoryItemCompositeDef crate_AK74 AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Some assembly required."),
	'LargeItem', true,
}),
PlaceObj('ModItemInventoryItemCompositeDef', {
	'Group', "Upgrade",
	'Id', "crate_AR15",
	'object_class', "MiscItem",
	'Repairable', false,
	'Icon', "Mod/Dwo4JJm/icons/cratebig.png",
	'SubIcon', "UI/Icons/Weapons/AR15",
	'DisplayName', T(400130899906, --[[ModItemInventoryItemCompositeDef crate_AR15 DisplayName]] "AR - AR-15 in a Crate"),
	'DisplayNamePlural', T(967766799495, --[[ModItemInventoryItemCompositeDef crate_AR15 DisplayNamePlural]] "AR - AR-15s in Crates"),
	'Description', T(752259247337, --[[ModItemInventoryItemCompositeDef crate_AR15 Description]] "An AR-15 in an old recycled army crate. "),
	'AdditionalHint', T(724602420746, --[[ModItemInventoryItemCompositeDef crate_AR15 AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Some assembly required."),
	'LargeItem', true,
}),
PlaceObj('ModItemInventoryItemCompositeDef', {
	'Group', "Upgrade",
	'Id', "crate_Famas",
	'object_class', "MiscItem",
	'Repairable', false,
	'Icon', "Mod/Dwo4JJm/icons/cratebig.png",
	'SubIcon', "UI/Icons/Weapons/FAMAS",
	'DisplayName', T(795419891370, --[[ModItemInventoryItemCompositeDef crate_Famas DisplayName]] "AR - FAMAS in a Crate"),
	'DisplayNamePlural', T(990615986053, --[[ModItemInventoryItemCompositeDef crate_Famas DisplayNamePlural]] "AR - FAMASs in Crates"),
	'Description', T(673731661705, --[[ModItemInventoryItemCompositeDef crate_Famas Description]] "A FAMAS in an army crate packed with a complimentary ration of wine and cheese."),
	'AdditionalHint', T(556781374135, --[[ModItemInventoryItemCompositeDef crate_Famas AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Some assembly required."),
	'LargeItem', true,
}),
PlaceObj('ModItemInventoryItemCompositeDef', {
	'Group', "Upgrade",
	'Id', "crate_AUG",
	'object_class', "MiscItem",
	'Repairable', false,
	'Icon', "Mod/Dwo4JJm/icons/cratebig.png",
	'SubIcon', "UI/Icons/Weapons/AUG",
	'DisplayName', T(533058654528, --[[ModItemInventoryItemCompositeDef crate_AUG DisplayName]] "AR - AUG in a Crate"),
	'DisplayNamePlural', T(626484430105, --[[ModItemInventoryItemCompositeDef crate_AUG DisplayNamePlural]] "AR - AUGs in Crates"),
	'Description', T(817636836233, --[[ModItemInventoryItemCompositeDef crate_AUG Description]] "A sci-fi looking AUG packed in a ratty old box."),
	'AdditionalHint', T(223653855278, --[[ModItemInventoryItemCompositeDef crate_AUG AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Some assembly required."),
	'LargeItem', true,
}),
PlaceObj('ModItemInventoryItemCompositeDef', {
	'Group', "Upgrade",
	'Id', "crate_M16A2",
	'object_class', "MiscItem",
	'Repairable', false,
	'Icon', "Mod/Dwo4JJm/icons/cratebig.png",
	'SubIcon', "UI/Icons/Weapons/M16A2",
	'DisplayName', T(557066017950, --[[ModItemInventoryItemCompositeDef crate_M16A2 DisplayName]] "AR - M16A2 in a Crate"),
	'DisplayNamePlural', T(308976994168, --[[ModItemInventoryItemCompositeDef crate_M16A2 DisplayNamePlural]] "AR - M16A2 in Crates"),
	'Description', T(834472972508, --[[ModItemInventoryItemCompositeDef crate_M16A2 Description]] "An M16A2 packed in an old army crate. The whiteout over the shipping details has worn away, revealing the United States as the source of these guns! Truly scandalous."),
	'AdditionalHint', T(544493209640, --[[ModItemInventoryItemCompositeDef crate_M16A2 AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Some assembly required."),
	'LargeItem', true,
}),
PlaceObj('ModItemInventoryItemCompositeDef', {
	'Group', "Upgrade",
	'Id', "crate_G36",
	'object_class', "MiscItem",
	'Repairable', false,
	'Icon', "Mod/Dwo4JJm/icons/cratebig.png",
	'SubIcon', "UI/Icons/Weapons/G36",
	'DisplayName', T(365980626461, --[[ModItemInventoryItemCompositeDef crate_G36 DisplayName]] "AR - G36 in a Crate"),
	'DisplayNamePlural', T(804611054368, --[[ModItemInventoryItemCompositeDef crate_G36 DisplayNamePlural]] "AR - G36s in Crates"),
	'Description', T(441256151341, --[[ModItemInventoryItemCompositeDef crate_G36 Description]] "A G36 in an old army crate. Some German postal worker must've gotten lost."),
	'AdditionalHint', T(186772327544, --[[ModItemInventoryItemCompositeDef crate_G36 AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Some assembly required."),
	'LargeItem', true,
}),
PlaceObj('ModItemInventoryItemCompositeDef', {
	'Group', "Upgrade",
	'Id', "crate_m14SAW",
	'object_class', "MiscItem",
	'Repairable', false,
	'Icon', "Mod/Dwo4JJm/icons/cratebig.png",
	'SubIcon', "UI/Icons/Weapons/M14",
	'DisplayName', T(131243814813, --[[ModItemInventoryItemCompositeDef crate_m14SAW DisplayName]] "AR - M14 in a Crate"),
	'DisplayNamePlural', T(824274870483, --[[ModItemInventoryItemCompositeDef crate_m14SAW DisplayNamePlural]] "AR - M14s in Crates"),
	'Description', T(640549767795, --[[ModItemInventoryItemCompositeDef crate_m14SAW Description]] "An M14 wedged in an army crate. Africans must not care about its ceremonial value."),
	'AdditionalHint', T(253240899110, --[[ModItemInventoryItemCompositeDef crate_m14SAW AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Some assembly required."),
	'LargeItem', true,
}),
PlaceObj('ModItemInventoryItemCompositeDef', {
	'Group', "Upgrade",
	'Id', "crate_Galil",
	'object_class', "MiscItem",
	'Repairable', false,
	'Icon', "Mod/Dwo4JJm/icons/cratebig.png",
	'SubIcon', "UI/Icons/Weapons/Galil",
	'DisplayName', T(855127780988, --[[ModItemInventoryItemCompositeDef crate_Galil DisplayName]] "AR - Galil in a Crate"),
	'DisplayNamePlural', T(521703578794, --[[ModItemInventoryItemCompositeDef crate_Galil DisplayNamePlural]] "AR - Galils in Crates"),
	'Description', T(238456190010, --[[ModItemInventoryItemCompositeDef crate_Galil Description]] "A Galil packed in an army box. The Israelis didn't even try to hide the origin, in fact they underlined it."),
	'AdditionalHint', T(891619041803, --[[ModItemInventoryItemCompositeDef crate_Galil AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Some assembly required."),
	'LargeItem', true,
}),
PlaceObj('ModItemInventoryItemCompositeDef', {
	'Group', "Upgrade",
	'Id', "crate_FNFAL",
	'object_class', "MiscItem",
	'Repairable', false,
	'Icon', "Mod/Dwo4JJm/icons/cratebig.png",
	'SubIcon', "UI/Icons/Weapons/FNFAL",
	'DisplayName', T(317936127408, --[[ModItemInventoryItemCompositeDef crate_FNFAL DisplayName]] "AR - FAL in a Crate"),
	'DisplayNamePlural', T(864833044446, --[[ModItemInventoryItemCompositeDef crate_FNFAL DisplayNamePlural]] "AR - FALs in Crates"),
	'Description', T(174606510869, --[[ModItemInventoryItemCompositeDef crate_FNFAL Description]] "A FAL in an old recycled army box. Good thing it's not a real right arm in a box or you might have to call the police."),
	'AdditionalHint', T(277298148833, --[[ModItemInventoryItemCompositeDef crate_FNFAL AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Some assembly required."),
	'LargeItem', true,
}),
PlaceObj('ModItemInventoryItemCompositeDef', {
	'Group', "Upgrade",
	'Id', "crate_MGL",
	'object_class', "MiscItem",
	'Repairable', false,
	'Icon', "Mod/Dwo4JJm/icons/cratebig.png",
	'SubIcon', "UI/Icons/Weapons/weapon_MGL",
	'DisplayName', T(110825400422, --[[ModItemInventoryItemCompositeDef crate_MGL DisplayName]] "BFG - MGL in a Crate"),
	'DisplayNamePlural', T(631496638718, --[[ModItemInventoryItemCompositeDef crate_MGL DisplayNamePlural]] "BFG - MGLs in Crates"),
	'Description', T(595859458178, --[[ModItemInventoryItemCompositeDef crate_MGL Description]] "An MGL thrown into an ill fitting box. If the cylinders are misaligned you'll be one pissed off ghost."),
	'AdditionalHint', T(505634560245, --[[ModItemInventoryItemCompositeDef crate_MGL AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Some assembly required."),
	'LargeItem', true,
}),
PlaceObj('ModItemInventoryItemCompositeDef', {
	'Group', "Upgrade",
	'Id', "crate_RPG7",
	'object_class', "MiscItem",
	'Repairable', false,
	'Icon', "Mod/Dwo4JJm/icons/cratebig.png",
	'SubIcon', "UI/Icons/Weapons/RPG-7",
	'DisplayName', T(420768669438, --[[ModItemInventoryItemCompositeDef crate_RPG7 DisplayName]] "BFG - RPG-7 in a Crate"),
	'DisplayNamePlural', T(781982113916, --[[ModItemInventoryItemCompositeDef crate_RPG7 DisplayNamePlural]] "BFG - RPG-7s in Crates"),
	'Description', T(803875524583, --[[ModItemInventoryItemCompositeDef crate_RPG7 Description]] "An RPG-7 sealed away in an army crate. Hopefully there won't be a warhead still in the thing when you open it."),
	'AdditionalHint', T(321047365726, --[[ModItemInventoryItemCompositeDef crate_RPG7 AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Some assembly required."),
	'LargeItem', true,
}),
PlaceObj('ModItemInventoryItemCompositeDef', {
	'Group', "Upgrade",
	'Id', "crate_mortarinventoryitem",
	'object_class', "MiscItem",
	'Repairable', false,
	'Icon', "Mod/Dwo4JJm/icons/cratebig.png",
	'SubIcon', "UI/Icons/Weapons/M224",
	'DisplayName', T(874311293085, --[[ModItemInventoryItemCompositeDef crate_mortarinventoryitem DisplayName]] "BFG - Mortar in a Crate"),
	'DisplayNamePlural', T(578569585496, --[[ModItemInventoryItemCompositeDef crate_mortarinventoryitem DisplayNamePlural]] "BFG - Mortars in Crates"),
	'Description', T(846294713732, --[[ModItemInventoryItemCompositeDef crate_mortarinventoryitem Description]] "A mortar inside of an army box. Thankfully this crate looks factory new, otherwise you'd probably be using the mortar to 'fire' your least favorite merc."),
	'AdditionalHint', T(123738935703, --[[ModItemInventoryItemCompositeDef crate_mortarinventoryitem AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Some assembly required."),
	'LargeItem', true,
}),
PlaceObj('ModItemInventoryItemCompositeDef', {
	'Group', "Upgrade",
	'Id', "crate_40mmflashbang",
	'object_class', "MiscItem",
	'Repairable', false,
	'Icon', "Mod/Dwo4JJm/icons/cratesmall.png",
	'SubIcon', "UI/Icons/Items/40mm_flashbang_grenade",
	'DisplayName', T(945487059711, --[[ModItemInventoryItemCompositeDef crate_40mmflashbang DisplayName]] "BFG - 40mm Flashbangs in a Crate"),
	'DisplayNamePlural', T(314041890934, --[[ModItemInventoryItemCompositeDef crate_40mmflashbang DisplayNamePlural]] "BFG - 40mm Flashbangs in Crates"),
	'Description', T(693808443238, --[[ModItemInventoryItemCompositeDef crate_40mmflashbang Description]] "9 40mm Flashbangs rolling around in a box. If this thing goes off it's gonna be heard and seen the world over."),
	'AdditionalHint', T(281936034468, --[[ModItemInventoryItemCompositeDef crate_40mmflashbang AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Some assembly required."),
}),
PlaceObj('ModItemInventoryItemCompositeDef', {
	'Group', "Upgrade",
	'Id', "crate_40mmfrag",
	'object_class', "MiscItem",
	'Repairable', false,
	'Icon', "Mod/Dwo4JJm/icons/cratesmall.png",
	'SubIcon', "UI/Icons/Items/40mm_frag_grenade",
	'DisplayName', T(870672498538, --[[ModItemInventoryItemCompositeDef crate_40mmfrag DisplayName]] "BFG - 40mm Frags in a Crate"),
	'DisplayNamePlural', T(364204368394, --[[ModItemInventoryItemCompositeDef crate_40mmfrag DisplayNamePlural]] "BFG - 40mm Frags in Crates"),
	'Description', T(949707931380, --[[ModItemInventoryItemCompositeDef crate_40mmfrag Description]] "6 40mm frag grenades rolling around in a box. Shake it as hard as you'd like, the grenades will let you know how they feel."),
	'AdditionalHint', T(532238839272, --[[ModItemInventoryItemCompositeDef crate_40mmfrag AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Some assembly required."),
}),
PlaceObj('ModItemInventoryItemCompositeDef', {
	'Group', "Upgrade",
	'Id', "crate_WarheadFrag",
	'object_class', "MiscItem",
	'Repairable', false,
	'Icon', "Mod/Dwo4JJm/icons/cratesmall.png",
	'SubIcon', "UI/Icons/Items/warhead_frag",
	'DisplayName', T(596244184573, --[[ModItemInventoryItemCompositeDef crate_WarheadFrag DisplayName]] "BFG - RPG Warheads in a Crate"),
	'DisplayNamePlural', T(724771088206, --[[ModItemInventoryItemCompositeDef crate_WarheadFrag DisplayNamePlural]] "BFG - RPG Warhead in Crates"),
	'Description', T(933051641383, --[[ModItemInventoryItemCompositeDef crate_WarheadFrag Description]] "5 RPG Warheads rolling around a box. Thank God the Soviets thought of safety caps."),
	'AdditionalHint', T(146442013256, --[[ModItemInventoryItemCompositeDef crate_WarheadFrag AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Some assembly required."),
}),
PlaceObj('ModItemInventoryItemCompositeDef', {
	'Group', "Upgrade",
	'Id', "crate_MortarShell_HE",
	'object_class', "MiscItem",
	'Repairable', false,
	'Icon', "Mod/Dwo4JJm/icons/cratesmall.png",
	'SubIcon', "UI/Icons/Items/mortar_shell_he",
	'DisplayName', T(770784095326, --[[ModItemInventoryItemCompositeDef crate_MortarShell_HE DisplayName]] "BFG - HE Shells in a Crate"),
	'DisplayNamePlural', T(198434698469, --[[ModItemInventoryItemCompositeDef crate_MortarShell_HE DisplayNamePlural]] "BFG - HE Shells in Crates"),
	'Description', T(433037047593, --[[ModItemInventoryItemCompositeDef crate_MortarShell_HE Description]] "10 HE Mortar Shells packed neatly in their original box. At least if it goes off it'll be quick and painless."),
	'AdditionalHint', T(709177100644, --[[ModItemInventoryItemCompositeDef crate_MortarShell_HE AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Some assembly required."),
}),
PlaceObj('ModItemInventoryItemCompositeDef', {
	'Group', "Upgrade",
	'Id', "crate_MortarShell_Gas",
	'object_class', "MiscItem",
	'Repairable', false,
	'Icon', "Mod/Dwo4JJm/icons/cratesmall.png",
	'SubIcon', "UI/Icons/Items/mortar_shell_gas",
	'DisplayName', T(145380572550, --[[ModItemInventoryItemCompositeDef crate_MortarShell_Gas DisplayName]] "BFG - Gas Shells in a Crate"),
	'DisplayNamePlural', T(221991294100, --[[ModItemInventoryItemCompositeDef crate_MortarShell_Gas DisplayNamePlural]] "BFG - Gas Shells in Crates"),
	'Description', T(951853297564, --[[ModItemInventoryItemCompositeDef crate_MortarShell_Gas Description]] "10 Gas Mortar Shells packed neatly in their original box. Either a series of war crimes or one massive fuckin' accident waiting to happen."),
	'AdditionalHint', T(810817135345, --[[ModItemInventoryItemCompositeDef crate_MortarShell_Gas AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Some assembly required."),
}),
PlaceObj('ModItemInventoryItemCompositeDef', {
	'Group', "Upgrade",
	'Id', "crate_MortarShell_Smoke",
	'object_class', "MiscItem",
	'Repairable', false,
	'Icon', "Mod/Dwo4JJm/icons/cratesmall.png",
	'SubIcon', "UI/Icons/Items/mortar_shell_smoke",
	'DisplayName', T(248823398222, --[[ModItemInventoryItemCompositeDef crate_MortarShell_Smoke DisplayName]] "BFG - Smoke Shells in a Crate"),
	'DisplayNamePlural', T(700417666814, --[[ModItemInventoryItemCompositeDef crate_MortarShell_Smoke DisplayNamePlural]] "BFG - Smoke Shells in Crates"),
	'Description', T(384260740145, --[[ModItemInventoryItemCompositeDef crate_MortarShell_Smoke Description]] "10 smoke mortar shells packed neatly in a crate. Nicotine free."),
	'AdditionalHint', T(661802545619, --[[ModItemInventoryItemCompositeDef crate_MortarShell_Smoke AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Some assembly required."),
}),
PlaceObj('ModItemInventoryItemCompositeDef', {
	'Group', "Upgrade",
	'Id', "crate_MG42",
	'object_class', "MiscItem",
	'Repairable', false,
	'Icon', "Mod/Dwo4JJm/icons/cratebig.png",
	'SubIcon', "UI/Icons/Weapons/MG42",
	'DisplayName', T(413207112980, --[[ModItemInventoryItemCompositeDef crate_MG42 DisplayName]] "MG - MG42 in a Crate"),
	'DisplayNamePlural', T(958197780064, --[[ModItemInventoryItemCompositeDef crate_MG42 DisplayNamePlural]] "MG - MG42s in Crates"),
	'Description', T(455594068766, --[[ModItemInventoryItemCompositeDef crate_MG42 Description]] "An MG42 in a crate. Get ready to teach some history lessons."),
	'AdditionalHint', T(372671534477, --[[ModItemInventoryItemCompositeDef crate_MG42 AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Some assembly required."),
	'LargeItem', true,
}),
PlaceObj('ModItemInventoryItemCompositeDef', {
	'Group', "Upgrade",
	'Id', "crate_RPK74",
	'object_class', "MiscItem",
	'Repairable', false,
	'Icon', "Mod/Dwo4JJm/icons/cratebig.png",
	'SubIcon', "UI/Icons/Weapons/RPK74",
	'DisplayName', T(907500902327, --[[ModItemInventoryItemCompositeDef crate_RPK74 DisplayName]] "MG - RPK-74 in a Crate"),
	'DisplayNamePlural', T(844253082925, --[[ModItemInventoryItemCompositeDef crate_RPK74 DisplayNamePlural]] "MG - RPK-74s in Crates"),
	'Description', T(328799090818, --[[ModItemInventoryItemCompositeDef crate_RPK74 Description]] "An RPK-74 in a crate. Erroneously labelled as 'really big AK-47'."),
	'AdditionalHint', T(675444559718, --[[ModItemInventoryItemCompositeDef crate_RPK74 AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Some assembly required."),
	'LargeItem', true,
}),
PlaceObj('ModItemInventoryItemCompositeDef', {
	'Group', "Upgrade",
	'Id', "crate_FNMinimi",
	'object_class', "MiscItem",
	'Repairable', false,
	'Icon', "Mod/Dwo4JJm/icons/cratebig.png",
	'SubIcon', "UI/Icons/Weapons/Minimi",
	'DisplayName', T(628286138356, --[[ModItemInventoryItemCompositeDef crate_FNMinimi DisplayName]] "MG - Minimi in a Crate"),
	'DisplayNamePlural', T(439441208253, --[[ModItemInventoryItemCompositeDef crate_FNMinimi DisplayNamePlural]] "MG - Minimis in Crates"),
	'Description', T(844590199101, --[[ModItemInventoryItemCompositeDef crate_FNMinimi Description]] "A Minimi in an army crate. Judging by the crate the gun is anything but mini. You'd sue for false advertising if Grand Chien's only legal system wasn't the gun inside."),
	'AdditionalHint', T(214495845127, --[[ModItemInventoryItemCompositeDef crate_FNMinimi AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Some assembly required."),
	'LargeItem', true,
}),
PlaceObj('ModItemInventoryItemCompositeDef', {
	'Group', "Upgrade",
	'Id', "crate_HK21",
	'object_class', "MiscItem",
	'Repairable', false,
	'Icon', "Mod/Dwo4JJm/icons/cratebig.png",
	'SubIcon', "UI/Icons/Weapons/HK21",
	'DisplayName', T(159800556711, --[[ModItemInventoryItemCompositeDef crate_HK21 DisplayName]] "MG - HK-21 in a Crate"),
	'DisplayNamePlural', T(591115422122, --[[ModItemInventoryItemCompositeDef crate_HK21 DisplayNamePlural]] "MG - HK-21s in Crates"),
	'Description', T(683216457933, --[[ModItemInventoryItemCompositeDef crate_HK21 Description]] "An HK-21 in an army crate. Labelled as a 'G8' but let's be clear: the contents of this box are anything but an inter-governmental political forum."),
	'AdditionalHint', T(329446027648, --[[ModItemInventoryItemCompositeDef crate_HK21 AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Some assembly required."),
	'LargeItem', true,
}),
PlaceObj('ModItemInventoryItemCompositeDef', {
	'Group', "Upgrade",
	'Id', "crate_DragunovSVD",
	'object_class', "MiscItem",
	'Repairable', false,
	'Icon', "Mod/Dwo4JJm/icons/cratebig.png",
	'SubIcon', "UI/Icons/Weapons/Dragunov",
	'DisplayName', T(620799105543, --[[ModItemInventoryItemCompositeDef crate_DragunovSVD DisplayName]] "RF - Dragunov in a Crate"),
	'DisplayNamePlural', T(337307306944, --[[ModItemInventoryItemCompositeDef crate_DragunovSVD DisplayNamePlural]] "RF - Dragunovs in Crates"),
	'Description', T(622202162929, --[[ModItemInventoryItemCompositeDef crate_DragunovSVD Description]] "An SVD in an army crate. Does not contain a manual on how that god damn scope works."),
	'AdditionalHint', T(612813567998, --[[ModItemInventoryItemCompositeDef crate_DragunovSVD AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Some assembly required."),
	'LargeItem', true,
}),
PlaceObj('ModItemInventoryItemCompositeDef', {
	'Group', "Upgrade",
	'Id', "crate_M24Sniper",
	'object_class', "MiscItem",
	'Repairable', false,
	'Icon', "Mod/Dwo4JJm/icons/cratebig.png",
	'SubIcon', "UI/Icons/Weapons/M24",
	'DisplayName', T(561413881459, --[[ModItemInventoryItemCompositeDef crate_M24Sniper DisplayName]] "RF - M24 in a Crate"),
	'DisplayNamePlural', T(709973211802, --[[ModItemInventoryItemCompositeDef crate_M24Sniper DisplayNamePlural]] "RF - M24s in Crates"),
	'Description', T(840645368220, --[[ModItemInventoryItemCompositeDef crate_M24Sniper Description]] "An M24 in a shabby looking crate. The US probably didn't part with this willingly."),
	'AdditionalHint', T(558524418371, --[[ModItemInventoryItemCompositeDef crate_M24Sniper AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Some assembly required."),
	'LargeItem', true,
}),
PlaceObj('ModItemInventoryItemCompositeDef', {
	'Group', "Valuables",
	'Id', "crate_PSG1",
	'object_class', "MiscItem",
	'Repairable', false,
	'Icon', "Mod/Dwo4JJm/icons/cratebig.png",
	'SubIcon', "UI/Icons/Weapons/PSG1",
	'DisplayName', T(111785543214, --[[ModItemInventoryItemCompositeDef crate_PSG1 DisplayName]] "RF - PSG1 in a Crate"),
	'DisplayNamePlural', T(748235265708, --[[ModItemInventoryItemCompositeDef crate_PSG1 DisplayNamePlural]] "RF - PSG1s in Crates"),
	'Description', T(642897230537, --[[ModItemInventoryItemCompositeDef crate_PSG1 Description]] "A PSG1 in a recycled army crate. Probably from South Africa or some other wildly corrupt user like the UK."),
	'AdditionalHint', T(731008314477, --[[ModItemInventoryItemCompositeDef crate_PSG1 AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Some assembly required."),
	'LargeItem', true,
}),
PlaceObj('ModItemInventoryItemCompositeDef', {
	'Group', "Upgrade",
	'Id', "crate_BarretM82",
	'object_class', "MiscItem",
	'Repairable', false,
	'Icon', "Mod/Dwo4JJm/icons/cratebig.png",
	'SubIcon', "UI/Icons/Weapons/M82",
	'DisplayName', T(811884853640, --[[ModItemInventoryItemCompositeDef crate_BarretM82 DisplayName]] "RF - M82 in a Crate"),
	'DisplayNamePlural', T(788386076051, --[[ModItemInventoryItemCompositeDef crate_BarretM82 DisplayNamePlural]] "RF - M82s in Crates"),
	'Description', T(167783371481, --[[ModItemInventoryItemCompositeDef crate_BarretM82 Description]] "A Barret M82 in a crate highly reinforced with duct tape."),
	'AdditionalHint', T(895874990197, --[[ModItemInventoryItemCompositeDef crate_BarretM82 AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Some assembly required."),
	'LargeItem', true,
}),
PlaceObj('ModItemInventoryItemCompositeDef', {
	'Group', "Upgrade",
	'Id', "crate_Uzi",
	'object_class', "MiscItem",
	'Repairable', false,
	'Icon', "Mod/Dwo4JJm/icons/cratesmall.png",
	'SubIcon', "UI/Icons/Weapons/UZI",
	'DisplayName', T(183802895325, --[[ModItemInventoryItemCompositeDef crate_Uzi DisplayName]] "SMG - Uzi in a Crate"),
	'DisplayNamePlural', T(702727322082, --[[ModItemInventoryItemCompositeDef crate_Uzi DisplayNamePlural]] "SMG - Uzis in Crates"),
	'Description', T(556352378930, --[[ModItemInventoryItemCompositeDef crate_Uzi Description]] "An Uzi in a crate. Comes with a manual on how to properly execute a drive-by."),
	'AdditionalHint', T(249586900188, --[[ModItemInventoryItemCompositeDef crate_Uzi AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Some assembly required."),
}),
PlaceObj('ModItemInventoryItemCompositeDef', {
	'Group', "Upgrade",
	'Id', "crate_MP5k",
	'object_class', "MiscItem",
	'Repairable', false,
	'Icon', "Mod/Dwo4JJm/icons/cratebig.png",
	'SubIcon', "UI/Icons/Weapons/MP5K",
	'DisplayName', T(572996393282, --[[ModItemInventoryItemCompositeDef crate_MP5k DisplayName]] "SMG - MP5k in a Crate"),
	'DisplayNamePlural', T(965010655631, --[[ModItemInventoryItemCompositeDef crate_MP5k DisplayNamePlural]] "SMG - MP5ks in Crates"),
	'Description', T(153594144183, --[[ModItemInventoryItemCompositeDef crate_MP5k Description]] "An MP5k in a comparatively huge box."),
	'AdditionalHint', T(244439799360, --[[ModItemInventoryItemCompositeDef crate_MP5k AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Some assembly required."),
	'LargeItem', true,
}),
PlaceObj('ModItemInventoryItemCompositeDef', {
	'Group', "Upgrade",
	'Id', "crate_Mp5",
	'object_class', "MiscItem",
	'Repairable', false,
	'Icon', "Mod/Dwo4JJm/icons/cratebig.png",
	'SubIcon', "UI/Icons/Weapons/MP5",
	'DisplayName', T(233825027596, --[[ModItemInventoryItemCompositeDef crate_Mp5 DisplayName]] "SMG - MP5 in a Crate"),
	'DisplayNamePlural', T(791646934837, --[[ModItemInventoryItemCompositeDef crate_Mp5 DisplayNamePlural]] "SMG - MP5s in Crates"),
	'Description', T(514708284215, --[[ModItemInventoryItemCompositeDef crate_Mp5 Description]] "An MP5 in a crate. Shipped directly from some police station in Wisconsin, they must've finally gotten their assault rifles."),
	'AdditionalHint', T(599651104224, --[[ModItemInventoryItemCompositeDef crate_Mp5 AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Some assembly required."),
	'LargeItem', true,
}),
PlaceObj('ModItemInventoryItemCompositeDef', {
	'Group', "Upgrade",
	'Id', "crate_AKSU",
	'object_class', "MiscItem",
	'Repairable', false,
	'Icon', "Mod/Dwo4JJm/icons/cratebig.png",
	'SubIcon', "UI/Icons/Weapons/AKSU",
	'DisplayName', T(997140126586, --[[ModItemInventoryItemCompositeDef crate_AKSU DisplayName]] "SMG - AKSU in a Crate"),
	'DisplayNamePlural', T(814615370538, --[[ModItemInventoryItemCompositeDef crate_AKSU DisplayNamePlural]] "SMG - AKSU in Crates"),
	'Description', T(544760783276, --[[ModItemInventoryItemCompositeDef crate_AKSU Description]] "An AKSU shipped from Soviet Russia. Considering the ink ran out halfway through printing the shipping details, the Ruskis must've been desperate for money to sell these."),
	'AdditionalHint', T(897249856521, --[[ModItemInventoryItemCompositeDef crate_AKSU AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Some assembly required."),
	'LargeItem', true,
}),
PlaceObj('ModItemInventoryItemCompositeDef', {
	'Id', "crate_M4Commando",
	'object_class', "MiscItem",
	'Repairable', false,
	'Icon', "Mod/Dwo4JJm/icons/cratebig.png",
	'SubIcon', "UI/Icons/Weapons/Commando",
	'DisplayName', T(897430255181, --[[ModItemInventoryItemCompositeDef crate_M4Commando DisplayName]] "SMG - M4 Commando in a Crate"),
	'DisplayNamePlural', T(980398940245, --[[ModItemInventoryItemCompositeDef crate_M4Commando DisplayNamePlural]] "SMG - M4 Commandos in Crates"),
	'Description', T(865480568030, --[[ModItemInventoryItemCompositeDef crate_M4Commando Description]] "An M4 Commando in a crate. Really the gun inside is probably assembled from 15 different generations of AR-15 and a few basement modifications, but who cares?"),
	'AdditionalHint', T(140972670389, --[[ModItemInventoryItemCompositeDef crate_M4Commando AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Some assembly required."),
	'LargeItem', true,
}),
PlaceObj('ModItemInventoryItemCompositeDef', {
	'Id', "crate_Auto5",
	'object_class', "MiscItem",
	'Repairable', false,
	'Icon', "Mod/Dwo4JJm/icons/cratebig.png",
	'SubIcon', "UI/Icons/Weapons/Browning Auto-5",
	'DisplayName', T(322607803064, --[[ModItemInventoryItemCompositeDef crate_Auto5 DisplayName]] "PG - Auto-5 in a Crate"),
	'DisplayNamePlural', T(188712074572, --[[ModItemInventoryItemCompositeDef crate_Auto5 DisplayNamePlural]] "PG - Auto-5s in Crates"),
	'Description', T(606035216838, --[[ModItemInventoryItemCompositeDef crate_Auto5 Description]] "An Auto-5 shotgun in a recycled old army crate. The crate is probably newer than the shotgun."),
	'AdditionalHint', T(312268711749, --[[ModItemInventoryItemCompositeDef crate_Auto5 AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Some assembly required."),
	'LargeItem', true,
}),
PlaceObj('ModItemInventoryItemCompositeDef', {
	'Id', "crate_M41Shotgun",
	'object_class', "MiscItem",
	'Repairable', false,
	'Icon', "Mod/Dwo4JJm/icons/cratebig.png",
	'SubIcon', "UI/Icons/Weapons/M1014",
	'DisplayName', T(231968582111, --[[ModItemInventoryItemCompositeDef crate_M41Shotgun DisplayName]] "PG - M1014 in a Crate"),
	'DisplayNamePlural', T(305025866531, --[[ModItemInventoryItemCompositeDef crate_M41Shotgun DisplayNamePlural]] "PG - M1014s in Crates"),
	'Description', T(258858154702, --[[ModItemInventoryItemCompositeDef crate_M41Shotgun Description]] "An M1014 shotgun in an army crate. The box is inscribed with 'Venni, vidi, vinsi'."),
	'AdditionalHint', T(205549958609, --[[ModItemInventoryItemCompositeDef crate_M41Shotgun AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Some assembly required."),
	'LargeItem', true,
}),
PlaceObj('ModItemInventoryItemCompositeDef', {
	'Id', "crate_AA12",
	'object_class', "MiscItem",
	'Repairable', false,
	'Icon', "Mod/Dwo4JJm/icons/cratebig.png",
	'SubIcon', "UI/Icons/Weapons/AA12",
	'DisplayName', T(865314084727, --[[ModItemInventoryItemCompositeDef crate_AA12 DisplayName]] "PG - AA-12 in a Crate"),
	'DisplayNamePlural', T(403747210203, --[[ModItemInventoryItemCompositeDef crate_AA12 DisplayNamePlural]] "PG - AA-12s in Crates"),
	'Description', T(651256394450, --[[ModItemInventoryItemCompositeDef crate_AA12 Description]] "An AA-12 in a nasty old crate. The AA-12 deserves better but gold plated boxes make shipping a lot harder."),
	'AdditionalHint', T(236039124206, --[[ModItemInventoryItemCompositeDef crate_AA12 AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Some assembly required."),
	'LargeItem', true,
}),
PlaceObj('ModItemInventoryItemCompositeDef', {
	'Id', "crate_Blackpowder",
	'object_class', "MiscItem",
	'Repairable', false,
	'Icon', "Mod/Dwo4JJm/icons/cratesmall.png",
	'SubIcon', "UI/Icons/Items/black_powder",
	'DisplayName', T(963947231296, --[[ModItemInventoryItemCompositeDef crate_Blackpowder DisplayName]] "EXP - Blackpowder Crate"),
	'DisplayNamePlural', T(250066387937, --[[ModItemInventoryItemCompositeDef crate_Blackpowder DisplayNamePlural]] "EXP - Blackpowder Crates"),
	'Description', T(462227232334, --[[ModItemInventoryItemCompositeDef crate_Blackpowder Description]] "A crate of 10 black powder loads. Use these for crafting, using powder kegs as a suicide weapon is no longer considered tactically viable."),
	'AdditionalHint', T(732750754205, --[[ModItemInventoryItemCompositeDef crate_Blackpowder AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Some assembly required."),
}),
PlaceObj('ModItemInventoryItemCompositeDef', {
	'Id', "crate_FragGrenade",
	'object_class', "MiscItem",
	'Repairable', false,
	'Icon', "Mod/Dwo4JJm/icons/cratesmall.png",
	'SubIcon', "UI/Icons/Weapons/Frag Grenade",
	'DisplayName', T(921967441741, --[[ModItemInventoryItemCompositeDef crate_FragGrenade DisplayName]] "EXP - Stick Grenade Crate"),
	'DisplayNamePlural', T(639066944505, --[[ModItemInventoryItemCompositeDef crate_FragGrenade DisplayNamePlural]] "EXP - Stick Grenades in Crates"),
	'Description', T(417341742079, --[[ModItemInventoryItemCompositeDef crate_FragGrenade Description]] "A box of old German stick grenades. They still work, sometimes even after its left your hands."),
	'AdditionalHint', T(833285293909, --[[ModItemInventoryItemCompositeDef crate_FragGrenade AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Some assembly required."),
}),
PlaceObj('ModItemInventoryItemCompositeDef', {
	'Id', "crate_HEGrenade",
	'object_class', "MiscItem",
	'Repairable', false,
	'Icon', "Mod/Dwo4JJm/icons/cratesmall.png",
	'SubIcon', "UI/Icons/Weapons/HEGrenade",
	'DisplayName', T(162493756728, --[[ModItemInventoryItemCompositeDef crate_HEGrenade DisplayName]] "EXP - Mk2 Grenade Crate"),
	'DisplayNamePlural', T(504437713599, --[[ModItemInventoryItemCompositeDef crate_HEGrenade DisplayNamePlural]] "EXP - MK2 Grenades in Crates"),
	'Description', T(899355085615, --[[ModItemInventoryItemCompositeDef crate_HEGrenade Description]] "A crate of pineapples grown in American factories, once popular across Europe and Pacific Islands throughout the early to mid 1940's."),
	'AdditionalHint', T(845101362213, --[[ModItemInventoryItemCompositeDef crate_HEGrenade AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Some assembly required."),
}),
PlaceObj('ModItemInventoryItemCompositeDef', {
	'Id', "crate_CamoLight",
	'object_class', "MiscItem",
	'Repairable', false,
	'Icon', "Mod/Dwo4JJm/icons/cratesmall.png",
	'SubIcon', "UI/Icons/Items/camo_armor_light",
	'DisplayName', T(974340759394, --[[ModItemInventoryItemCompositeDef crate_CamoLight DisplayName]] "GEAR - Camo Suit Crate"),
	'DisplayNamePlural', T(878778602165, --[[ModItemInventoryItemCompositeDef crate_CamoLight DisplayNamePlural]] "GEAR - Camo Suits in Crates"),
	'Description', T(168094846606, --[[ModItemInventoryItemCompositeDef crate_CamoLight Description]] "A nice little camouflage suit, neatly packed up. Shame nobody will see how cool you look in it."),
	'AdditionalHint', T(470195268597, --[[ModItemInventoryItemCompositeDef crate_CamoLight AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Some assembly required."),
}),
PlaceObj('ModItemInventoryItemCompositeDef', {
	'Id', "crate_camomedium",
	'object_class', "MiscItem",
	'Repairable', false,
	'Icon', "Mod/Dwo4JJm/icons/cratesmall.png",
	'SubIcon', "UI/Icons/Items/camo_armor_medium",
	'DisplayName', T(387494172201, --[[ModItemInventoryItemCompositeDef crate_camomedium DisplayName]] "GEAR - Camo Suit (Medium) in Crate"),
	'DisplayNamePlural', T(304863591331, --[[ModItemInventoryItemCompositeDef crate_camomedium DisplayNamePlural]] "GEAR - Camo Suits (Medium) in Crates"),
	'Description', T(682561134973, --[[ModItemInventoryItemCompositeDef crate_camomedium Description]] "A heavier duty camouflage suit in a box. The box might look empty at first glance."),
	'AdditionalHint', T(550010834158, --[[ModItemInventoryItemCompositeDef crate_camomedium AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Some assembly required."),
}),
PlaceObj('ModItemInventoryItemCompositeDef', {
	'Id', "crate_gasmask",
	'object_class', "MiscItem",
	'Repairable', false,
	'Icon', "Mod/Dwo4JJm/icons/cratesmall.png",
	'SubIcon', "UI/Icons/Items/gas_mask",
	'DisplayName', T(573549917177, --[[ModItemInventoryItemCompositeDef crate_gasmask DisplayName]] "GEAR - Gas Mask in Crate"),
	'DisplayNamePlural', T(933765678283, --[[ModItemInventoryItemCompositeDef crate_gasmask DisplayNamePlural]] "GEAR - Gas Masks in Crates"),
	'Description', T(173419304704, --[[ModItemInventoryItemCompositeDef crate_gasmask Description]] "A gas mask in a crate. Seems the issued bag would've made more sense but you can't have everything."),
	'AdditionalHint', T(276498566467, --[[ModItemInventoryItemCompositeDef crate_gasmask AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Some assembly required."),
}),
PlaceObj('ModItemInventoryItemCompositeDef', {
	'Id', "crate_nightvisiongoggles",
	'object_class', "MiscItem",
	'Repairable', false,
	'Icon', "Mod/Dwo4JJm/icons/cratesmall.png",
	'SubIcon', "UI/Icons/Items/night_vision",
	'DisplayName', T(782391825482, --[[ModItemInventoryItemCompositeDef crate_nightvisiongoggles DisplayName]] "GEAR - Night Vision Crate"),
	'DisplayNamePlural', T(907254896337, --[[ModItemInventoryItemCompositeDef crate_nightvisiongoggles DisplayNamePlural]] "GEAR - Night Vision Crate"),
	'Description', T(884731768906, --[[ModItemInventoryItemCompositeDef crate_nightvisiongoggles Description]] "Night vision goggles packed up in a box. Includes a bag full of different batteries and a roll of Mentos that someone must've thought was a battery."),
	'AdditionalHint', T(637037726586, --[[ModItemInventoryItemCompositeDef crate_nightvisiongoggles AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Some assembly required."),
}),
PlaceObj('ModItemInventoryItemCompositeDef', {
	'Id', "crate_KevlarSet",
	'object_class', "MiscItem",
	'Repairable', false,
	'Icon', "Mod/Dwo4JJm/icons/cratebig.png",
	'SubIcon', "UI/Icons/Items/kevlar_helmet",
	'DisplayName', T(634493963721, --[[ModItemInventoryItemCompositeDef crate_KevlarSet DisplayName]] "GEAR - Kevlar Set"),
	'DisplayNamePlural', T(347944061935, --[[ModItemInventoryItemCompositeDef crate_KevlarSet DisplayNamePlural]] "GEAR - Kevlar Sets"),
	'Description', T(147624749348, --[[ModItemInventoryItemCompositeDef crate_KevlarSet Description]] "A Kevlar vest and helmet inside of a crate. Slowing coming into fashion across Grand Chien."),
	'AdditionalHint', T(973752969887, --[[ModItemInventoryItemCompositeDef crate_KevlarSet AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Some assembly required."),
	'LargeItem', true,
}),
PlaceObj('ModItemInventoryItemCompositeDef', {
	'Id', "crate_KevlarSet_1",
	'object_class', "MiscItem",
	'Repairable', false,
	'Icon', "Mod/Dwo4JJm/icons/cratebig.png",
	'SubIcon', "UI/Icons/Items/kevlar_armor",
	'DisplayName', T(725877553732, --[[ModItemInventoryItemCompositeDef crate_KevlarSet_1 DisplayName]] "GEAR - SpecOps Kevlar Set"),
	'DisplayNamePlural', T(577885349238, --[[ModItemInventoryItemCompositeDef crate_KevlarSet_1 DisplayNamePlural]] "GEAR - SpecOps Kevlar Sets"),
	'Description', T(793773408364, --[[ModItemInventoryItemCompositeDef crate_KevlarSet_1 Description]] "A SpecOps Kevlar vest, leggings and helmet inside of a crate. Slowing coming into fashion across Grand Chien."),
	'AdditionalHint', T(496658979643, --[[ModItemInventoryItemCompositeDef crate_KevlarSet_1 AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Some assembly required."),
	'LargeItem', true,
}),
PlaceObj('ModItemInventoryItemCompositeDef', {
	'Id', "crate_HeavySet",
	'object_class', "MiscItem",
	'Repairable', false,
	'Icon', "Mod/Dwo4JJm/icons/cratebig.png",
	'SubIcon', "UI/Icons/Items/heavy_helmet",
	'DisplayName', T(574920567372, --[[ModItemInventoryItemCompositeDef crate_HeavySet DisplayName]] "GEAR - Heavy Armor Set"),
	'DisplayNamePlural', T(876440814308, --[[ModItemInventoryItemCompositeDef crate_HeavySet DisplayNamePlural]] "GEAR - Heavy Armor Sets"),
	'Description', T(951744644235, --[[ModItemInventoryItemCompositeDef crate_HeavySet Description]] "A heavy suit of body armor and accompanying helmet. Some say its overkill for Grand Chien, we call those people old fashioned."),
	'AdditionalHint', T(483256710132, --[[ModItemInventoryItemCompositeDef crate_HeavySet AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Some assembly required."),
	'LargeItem', true,
}),
PlaceObj('ModItemInventoryItemCompositeDef', {
	'Id', "crate_44cal",
	'object_class', "MiscItem",
	'Repairable', false,
	'Icon', "Mod/Dwo4JJm/icons/crateammo.png",
	'SubIcon', "UI/Icons/Items/44_cal_bullets_basic",
	'DisplayName', T(356912356824, --[[ModItemInventoryItemCompositeDef crate_44cal DisplayName]] "MUN - .44 Ammo Box"),
	'DisplayNamePlural', T(863120862821, --[[ModItemInventoryItemCompositeDef crate_44cal DisplayNamePlural]] "MUN - .44 Ammo Boxes"),
	'Description', T(320941548585, --[[ModItemInventoryItemCompositeDef crate_44cal Description]] "A pack of 60 rounds of .44 caliber. On the label is an advertisement for their branded boxes of 44 .60 caliber bullets.\n(ALL SALES FINAL)"),
	'AdditionalHint', T(516786243756, --[[ModItemInventoryItemCompositeDef crate_44cal AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Some assembly required."),
}),
PlaceObj('ModItemInventoryItemCompositeDef', {
	'Id', "crate_12gaugebuckshot",
	'object_class', "MiscItem",
	'Repairable', false,
	'Icon', "Mod/Dwo4JJm/icons/crateammo.png",
	'SubIcon', "UI/Icons/Items/12_gauge_bullets_buckshot",
	'DisplayName', T(197065198873, --[[ModItemInventoryItemCompositeDef crate_12gaugebuckshot DisplayName]] "MUN - 12 Gauge Buckshot Box"),
	'DisplayNamePlural', T(186008192750, --[[ModItemInventoryItemCompositeDef crate_12gaugebuckshot DisplayNamePlural]] "MUN - 12 Gauge Buckshot Boxes"),
	'Description', T(593297705930, --[[ModItemInventoryItemCompositeDef crate_12gaugebuckshot Description]] "A 50 shell box of 12 gauge buckshot. Fishermen use this ammo to create chum from their fellow man's heads."),
	'AdditionalHint', T(314667687630, --[[ModItemInventoryItemCompositeDef crate_12gaugebuckshot AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Some assembly required."),
}),
PlaceObj('ModItemInventoryItemCompositeDef', {
	'Id', "crate_50bmg",
	'object_class', "MiscItem",
	'Repairable', false,
	'Icon', "Mod/Dwo4JJm/icons/crateammo.png",
	'SubIcon', "UI/Icons/Items/50bmg_basic",
	'DisplayName', T(536424979620, --[[ModItemInventoryItemCompositeDef crate_50bmg DisplayName]] "MUN - 50 BMG Box"),
	'DisplayNamePlural', T(378673227338, --[[ModItemInventoryItemCompositeDef crate_50bmg DisplayNamePlural]] "MUN - 50 BMG Boxes"),
	'Description', T(526452276318, --[[ModItemInventoryItemCompositeDef crate_50bmg Description]] "50 rounds of .50 BMG. This box is bigger than any gun you're carrying."),
	'AdditionalHint', T(443599589971, --[[ModItemInventoryItemCompositeDef crate_50bmg AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Some assembly required."),
}),
PlaceObj('ModItemInventoryItemCompositeDef', {
	'Id', "crate_556",
	'object_class', "MiscItem",
	'Repairable', false,
	'Icon', "Mod/Dwo4JJm/icons/crateammo.png",
	'SubIcon', "UI/Icons/Items/556_nato_bullets_basic",
	'DisplayName', T(871165643254, --[[ModItemInventoryItemCompositeDef crate_556 DisplayName]] "MUN - 556 Ammo Box"),
	'DisplayNamePlural', T(205654873498, --[[ModItemInventoryItemCompositeDef crate_556 DisplayNamePlural]] "MUN - 556 Ammo Boxes"),
	'Description', T(829967098601, --[[ModItemInventoryItemCompositeDef crate_556 Description]] "150 rounds of 556. Intermediate rounds like 556 became popular in the 70's after the realization that the only body armor available at the time was hallucinogenic drugs."),
	'AdditionalHint', T(567342036838, --[[ModItemInventoryItemCompositeDef crate_556 AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Some assembly required."),
}),
PlaceObj('ModItemInventoryItemCompositeDef', {
	'Id', "crate_556_sabre",
	'object_class', "MiscItem",
	'Repairable', false,
	'Icon', "Mod/Dwo4JJm/icons/crateammo.png",
	'SubIcon', "Mod/Dwo4JJm/icons/nato556sabre.png",
	'DisplayName', T(649840815308, --[[ModItemInventoryItemCompositeDef crate_556_sabre DisplayName]] "MUN - 556 Sabre Ammo Box"),
	'DisplayNamePlural', T(610896607013, --[[ModItemInventoryItemCompositeDef crate_556_sabre DisplayNamePlural]] "MUN - 556 Sabre Ammo Boxes"),
	'Description', T(322285447316, --[[ModItemInventoryItemCompositeDef crate_556_sabre Description]] "150 rounds of 556. Intermediate rounds like 556 became popular in the 70's after the realization that the only body armor available at the time was hallucinogenic drugs."),
	'AdditionalHint', T(874368814898, --[[ModItemInventoryItemCompositeDef crate_556_sabre AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Some assembly required."),
}),
PlaceObj('ModItemInventoryItemCompositeDef', {
	'Id', "crate_556_p",
	'object_class', "MiscItem",
	'Repairable', false,
	'Icon', "Mod/Dwo4JJm/icons/crateammo.png",
	'SubIcon', "UI/Icons/Items/556_nato_bullets_match",
	'DisplayName', T(902471475179, --[[ModItemInventoryItemCompositeDef crate_556_p DisplayName]] "MUN - 556 +P Ammo Box"),
	'DisplayNamePlural', T(609115154421, --[[ModItemInventoryItemCompositeDef crate_556_p DisplayNamePlural]] "MUN - 556 +P Ammo Boxes"),
	'Description', T(807806326425, --[[ModItemInventoryItemCompositeDef crate_556_p Description]] "150 rounds of 556 +P. Intermediate rounds like 556 became popular in the 70's after the realization that the only body armor available at the time was hallucinogenic drugs."),
	'AdditionalHint', T(992241171916, --[[ModItemInventoryItemCompositeDef crate_556_p AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Some assembly required."),
}),
PlaceObj('ModItemInventoryItemCompositeDef', {
	'Id', "crate_556_phosphor",
	'object_class', "MiscItem",
	'Repairable', false,
	'Icon', "Mod/Dwo4JJm/icons/crateammo.png",
	'SubIcon', "UI/Icons/Items/556_nato_bullets_armor_piercing",
	'DisplayName', T(233756349460, --[[ModItemInventoryItemCompositeDef crate_556_phosphor DisplayName]] "MUN - 556 WP Ammo Box"),
	'DisplayNamePlural', T(389937801193, --[[ModItemInventoryItemCompositeDef crate_556_phosphor DisplayNamePlural]] "MUN - 556 WP Ammo Boxes"),
	'Description', T(767512253435, --[[ModItemInventoryItemCompositeDef crate_556_phosphor Description]] "150 rounds of 556 Phosphor. Intermediate rounds like 556 became popular in the 70's after the realization that the only body armor available at the time was hallucinogenic drugs."),
	'AdditionalHint', T(493303866652, --[[ModItemInventoryItemCompositeDef crate_556_phosphor AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Some assembly required."),
}),
PlaceObj('ModItemInventoryItemCompositeDef', {
	'Id', "crate_762nato",
	'object_class', "MiscItem",
	'Repairable', false,
	'Icon', "Mod/Dwo4JJm/icons/crateammo.png",
	'SubIcon', "UI/Icons/Items/762_nato_basic",
	'DisplayName', T(767248946239, --[[ModItemInventoryItemCompositeDef crate_762nato DisplayName]] "MUN - 762 NATO Ammo Box"),
	'DisplayNamePlural', T(748760872852, --[[ModItemInventoryItemCompositeDef crate_762nato DisplayNamePlural]] "MUN - 762 NATO Ammo Boxes"),
	'Description', T(449631251962, --[[ModItemInventoryItemCompositeDef crate_762nato Description]] "100 rounds of 762 NATO. Despite NATO infantry using 556 for their rifles, 762 NATO remains useful for flexing military power and budget on the Third World."),
	'AdditionalHint', T(362814060398, --[[ModItemInventoryItemCompositeDef crate_762nato AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Some assembly required."),
}),
PlaceObj('ModItemInventoryItemCompositeDef', {
	'Id', "crate_762WP",
	'object_class', "MiscItem",
	'Repairable', false,
	'Icon', "Mod/Dwo4JJm/icons/crateammo.png",
	'SubIcon', "UI/Icons/Items/762_wp_bullets_basic",
	'DisplayName', T(639932324215, --[[ModItemInventoryItemCompositeDef crate_762WP DisplayName]] "MUN - 762 WP Box"),
	'DisplayNamePlural', T(731672533372, --[[ModItemInventoryItemCompositeDef crate_762WP DisplayNamePlural]] "MUN - 762 WP Boxes"),
	'Description', T(903253403400, --[[ModItemInventoryItemCompositeDef crate_762WP Description]] "150 rounds of 762 WP. More important than food or water."),
	'AdditionalHint', T(341767543789, --[[ModItemInventoryItemCompositeDef crate_762WP AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Some assembly required."),
}),
PlaceObj('ModItemInventoryItemCompositeDef', {
	'Id', "crate_9mm",
	'object_class', "MiscItem",
	'Repairable', false,
	'Icon', "Mod/Dwo4JJm/icons/crateammo.png",
	'SubIcon', "UI/Icons/Items/9mm_bullets_basic",
	'DisplayName', T(385523385349, --[[ModItemInventoryItemCompositeDef crate_9mm DisplayName]] "MUN - 9mm Box"),
	'DisplayNamePlural', T(689786839748, --[[ModItemInventoryItemCompositeDef crate_9mm DisplayNamePlural]] "MUN - 9mm Boxes"),
	'Description', T(817987208630, --[[ModItemInventoryItemCompositeDef crate_9mm Description]] "200 rounds of 9mm. 9mm has largely fallen out of favor in Africa since the 70's with the proliferation of rifles and heavy weapons, which means more for you."),
	'AdditionalHint', T(478599390892, --[[ModItemInventoryItemCompositeDef crate_9mm AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Some assembly required."),
}),
PlaceObj('ModItemInventoryItemCompositeDef', {
	'Id', "crate_Explosives",
	'object_class', "MiscItem",
	'Repairable', false,
	'Icon', "Mod/Dwo4JJm/icons/cratesmall.png",
	'SubIcon', "UI/Icons/Items/c4",
	'DisplayName', T(459786060575, --[[ModItemInventoryItemCompositeDef crate_Explosives DisplayName]] "EXP - Explosives Crate"),
	'DisplayNamePlural', T(627607930820, --[[ModItemInventoryItemCompositeDef crate_Explosives DisplayNamePlural]] "EXP - Explosives Crates"),
	'Description', T(582425233513, --[[ModItemInventoryItemCompositeDef crate_Explosives Description]] "A crate of 2 blocks of C4 and 3 bundles of TNT. Instructions and detonators not included for legal purposes."),
	'AdditionalHint', T(313829098721, --[[ModItemInventoryItemCompositeDef crate_Explosives AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Some assembly required."),
}),
PlaceObj('ModItemInventoryItemCompositeDef', {
	'Id', "crate_RemoteDets",
	'object_class', "MiscItem",
	'Repairable', false,
	'Icon', "Mod/Dwo4JJm/icons/cratesmall.png",
	'SubIcon', "UI/Icons/Items/combination_detonator_remote",
	'DisplayName', T(678944354905, --[[ModItemInventoryItemCompositeDef crate_RemoteDets DisplayName]] "EXP - Remote Detonator Crate"),
	'DisplayNamePlural', T(107306178392, --[[ModItemInventoryItemCompositeDef crate_RemoteDets DisplayNamePlural]] "EXP - Remote Detonator Crates"),
	'Description', T(857432560853, --[[ModItemInventoryItemCompositeDef crate_RemoteDets Description]] "A 3 pack of remote detonators and a remote. TV not included."),
	'AdditionalHint', T(609315685460, --[[ModItemInventoryItemCompositeDef crate_RemoteDets AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Some assembly required."),
}),
PlaceObj('ModItemInventoryItemCompositeDef', {
	'Id', "crate_ProxyDets",
	'object_class', "MiscItem",
	'Repairable', false,
	'Icon', "Mod/Dwo4JJm/icons/cratesmall.png",
	'SubIcon', "UI/Icons/Items/combination_detonator_proximity",
	'DisplayName', T(521884450170, --[[ModItemInventoryItemCompositeDef crate_ProxyDets DisplayName]] "EXP - Proximity Detonator Crate"),
	'DisplayNamePlural', T(931425596882, --[[ModItemInventoryItemCompositeDef crate_ProxyDets DisplayNamePlural]] "EXP - Proximity Detonator Crates"),
	'Description', T(673934081573, --[[ModItemInventoryItemCompositeDef crate_ProxyDets Description]] "A 3 pack of proximity detonators bundled with handy instructions from the Mujahideen."),
	'AdditionalHint', T(678993366579, --[[ModItemInventoryItemCompositeDef crate_ProxyDets AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Some assembly required."),
}),
PlaceObj('ModItemInventoryItemCompositeDef', {
	'Id', "crate_TimeDets",
	'object_class', "MiscItem",
	'Repairable', false,
	'Icon', "Mod/Dwo4JJm/icons/cratesmall.png",
	'SubIcon', "UI/Icons/Items/combination_detonator_time",
	'DisplayName', T(792683216793, --[[ModItemInventoryItemCompositeDef crate_TimeDets DisplayName]] "EXP - Time Detonator Crate"),
	'DisplayNamePlural', T(559790904358, --[[ModItemInventoryItemCompositeDef crate_TimeDets DisplayNamePlural]] "EXP - Time Detonator Crates"),
	'Description', T(215392113114, --[[ModItemInventoryItemCompositeDef crate_TimeDets Description]] "A crate of 3 time detonators. Comes with free instructions from the IRA!"),
	'AdditionalHint', T(138494965337, --[[ModItemInventoryItemCompositeDef crate_TimeDets AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Some assembly required."),
}),
PlaceObj('ModItemInventoryItemCompositeDef', {
	'Id', "crate_plates",
	'object_class', "MiscItem",
	'Repairable', false,
	'Icon', "Mod/Dwo4JJm/icons/cratesmall.png",
	'SubIcon', "UI/Icons/Items/combination_ceramic_plates",
	'DisplayName', T(690253360859, --[[ModItemInventoryItemCompositeDef crate_plates DisplayName]] "GEAR - Ceramic Plate Crate"),
	'DisplayNamePlural', T(661865894336, --[[ModItemInventoryItemCompositeDef crate_plates DisplayNamePlural]] "GEAR - Ceramic Plate Crates"),
	'Description', T(273121936001, --[[ModItemInventoryItemCompositeDef crate_plates Description]] "Two ceramic plates in a crate. Comes with a free magazine on exercises you can perform with them!"),
	'AdditionalHint', T(846157204912, --[[ModItemInventoryItemCompositeDef crate_plates AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Some assembly required."),
}),
PlaceObj('ModItemInventoryItemCompositeDef', {
	'Id', "crate_lockpick",
	'object_class', "MiscItem",
	'Repairable', false,
	'Icon', "Mod/Dwo4JJm/icons/cratesmall.png",
	'SubIcon', "UI/Icons/Items/lockpick",
	'DisplayName', T(384340918729, --[[ModItemInventoryItemCompositeDef crate_lockpick DisplayName]] "TOOL - Lockpicking Set"),
	'DisplayNamePlural', T(543706846957, --[[ModItemInventoryItemCompositeDef crate_lockpick DisplayNamePlural]] "TOOL - Lockpicking Sets"),
	'Description', T(949782931528, --[[ModItemInventoryItemCompositeDef crate_lockpick Description]] "A small crate containing a lockpicking set and instructions for common locks that neighbors, sorority houses, and liquor stores use."),
	'AdditionalHint', T(326693938168, --[[ModItemInventoryItemCompositeDef crate_lockpick AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Some assembly required."),
}),
PlaceObj('ModItemInventoryItemCompositeDef', {
	'Id', "crate_firstaidkit",
	'object_class', "MiscItem",
	'Repairable', false,
	'Icon', "Mod/Dwo4JJm/icons/cratesmall.png",
	'SubIcon', "UI/Icons/Items/first_aid_kit",
	'DisplayName', T(593914860085, --[[ModItemInventoryItemCompositeDef crate_firstaidkit DisplayName]] "TOOL - First Aid Kit"),
	'DisplayNamePlural', T(365005910383, --[[ModItemInventoryItemCompositeDef crate_firstaidkit DisplayNamePlural]] "TOOL - First Aid Kit"),
	'Description', T(114672000142, --[[ModItemInventoryItemCompositeDef crate_firstaidkit Description]] "A box with a military first aid kit with complimentary advisory pamphlet on how gunshot wounds occur."),
	'AdditionalHint', T(288093365431, --[[ModItemInventoryItemCompositeDef crate_firstaidkit AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Some assembly required."),
}),
PlaceObj('ModItemInventoryItemCompositeDef', {
	'Id', "crate_machete",
	'object_class', "MiscItem",
	'Repairable', false,
	'Icon', "Mod/Dwo4JJm/icons/cratesmall.png",
	'SubIcon', "UI/Icons/Weapons/Machete",
	'DisplayName', T(719332313824, --[[ModItemInventoryItemCompositeDef crate_machete DisplayName]] "GEAR - Machete Box"),
	'DisplayNamePlural', T(698964104746, --[[ModItemInventoryItemCompositeDef crate_machete DisplayNamePlural]] "GEAR - Machete Boxes"),
	'Description', T(359969075819, --[[ModItemInventoryItemCompositeDef crate_machete Description]] "A box with a machete, the choice sidearm of African armies, militias and civilians."),
	'AdditionalHint', T(707780227189, --[[ModItemInventoryItemCompositeDef crate_machete AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Some assembly required."),
}),
PlaceObj('ModItemInventoryItemCompositeDef', {
	'Id', "crate_Winchester",
	'object_class', "MiscItem",
	'Repairable', false,
	'Icon', "Mod/Dwo4JJm/icons/cratebig.png",
	'SubIcon', "UI/Icons/Weapons/Winchester",
	'DisplayName', T(824591674119, --[[ModItemInventoryItemCompositeDef crate_Winchester DisplayName]] "RF - Winchester Crate"),
	'DisplayNamePlural', T(120469118873, --[[ModItemInventoryItemCompositeDef crate_Winchester DisplayNamePlural]] "RF - Winchester Crates"),
	'Description', T(183296368904, --[[ModItemInventoryItemCompositeDef crate_Winchester Description]] "A Winchester rifle in a crate. Be the envy of all those outlaws still toting around six-shooters."),
	'AdditionalHint', T(350397647192, --[[ModItemInventoryItemCompositeDef crate_Winchester AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Some assembly required."),
}),
PlaceObj('ModItemInventoryItemCompositeDef', {
	'Id', "crate_knife",
	'object_class', "MiscItem",
	'Repairable', false,
	'Icon', "Mod/Dwo4JJm/icons/cratesmall.png",
	'SubIcon', "UI/Icons/Weapons/Combat Knife Balanced",
	'DisplayName', T(419238412903, --[[ModItemInventoryItemCompositeDef crate_knife DisplayName]] "GEAR - Knife Box"),
	'DisplayNamePlural', T(486805489661, --[[ModItemInventoryItemCompositeDef crate_knife DisplayNamePlural]] "GEAR - Knife Boxes"),
	'Description', T(242779806004, --[[ModItemInventoryItemCompositeDef crate_knife Description]] "A well balanced knife in its factory crate. You'd read the company slogan if the knife wasn't already stabbing through the box."),
	'AdditionalHint', T(434550144532, --[[ModItemInventoryItemCompositeDef crate_knife AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Some assembly required."),
}),
PlaceObj('ModItemInventoryItemCompositeDef', {
	'Group', "Armor - Kevlar",
	'Id', "Armo_Spec_Ops_Vest_1",
	'object_class', "Armor",
	'RepairCost', 40,
	'Degradation', 6,
	'ScrapParts', 4,
	'Icon', "UI/Icons/Items/kevlar_armor",
	'SubIcon', "UI/Icons/Items/padded",
	'ItemType', "Armor",
	'DisplayName', T(485133896067, --[[ModItemInventoryItemCompositeDef Armo_Spec_Ops_Vest_1 DisplayName]] "Spec-Ops Vest and Camofalage"),
	'DisplayNamePlural', T(833970335801, --[[ModItemInventoryItemCompositeDef Armo_Spec_Ops_Vest_1 DisplayNamePlural]] "Spec-Ops Vests and Camofalages"),
	'Description', "",
	'AdditionalHint', T(409750429217, --[[ModItemInventoryItemCompositeDef Armo_Spec_Ops_Vest_1 AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Damage reduction improved by Weave Padding"),
	'Cumbersome', true,
	'is_valuable', true,
	'Cost', 2500,
	'PenetrationClass', 3,
	'DamageReduction', 45,
	'AdditionalReduction', 40,
	'ProtectedBodyParts', set( "Arms", "Torso" ),
	'Camouflage', true,
}),
PlaceObj('ModItemInventoryItemCompositeDef', {
	'Group', "Armor - Flak",
	'Id', "Armor_Spec_Ops_leggings_1",
	'object_class', "Armor",
	'RepairCost', 30,
	'Degradation', 5,
	'ScrapParts', 4,
	'Icon', "UI/Icons/Items/flak_leggings",
	'SubIcon', "UI/Icons/Items/padded",
	'ItemType', "Armor",
	'DisplayName', T(328511827199, --[[ModItemInventoryItemCompositeDef Armor_Spec_Ops_leggings_1 DisplayName]] "Spec-Ops Camofalage Leggings"),
	'DisplayNamePlural', T(978438966967, --[[ModItemInventoryItemCompositeDef Armor_Spec_Ops_leggings_1 DisplayNamePlural]] "Spec-Ops Camofalage Leggings"),
	'Description', "",
	'AdditionalHint', T(881274878786, --[[ModItemInventoryItemCompositeDef Armor_Spec_Ops_leggings_1 AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Damage reduction improved by Weave Padding"),
	'is_valuable', true,
	'Cost', 2000,
	'Slot', "Legs",
	'PenetrationClass', 3,
	'DamageReduction', 45,
	'AdditionalReduction', 30,
	'ProtectedBodyParts', set( "Groin", "Legs" ),
	'Camouflage', true,
}),
PlaceObj('ModItemInventoryItemCompositeDef', {
	'Group', "Armor - Kevlar",
	'Id', "Armor_Spec_Ops_Helmet_1",
	'object_class', "Armor",
	'RepairCost', 30,
	'Degradation', 5,
	'ScrapParts', 2,
	'Icon', "UI/Icons/Items/kevlar_helmet",
	'SubIcon', "UI/Icons/Items/padded",
	'ItemType', "Armor",
	'DisplayName', T(467220643808, --[[ModItemInventoryItemCompositeDef Armor_Spec_Ops_Helmet_1 DisplayName]] "Spec-Ops Helmet"),
	'DisplayNamePlural', T(316857884348, --[[ModItemInventoryItemCompositeDef Armor_Spec_Ops_Helmet_1 DisplayNamePlural]] "Spec-Ops Helmets"),
	'Description', "",
	'AdditionalHint', T(292340171816, --[[ModItemInventoryItemCompositeDef Armor_Spec_Ops_Helmet_1 AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Damage reduction improved by Weave Padding"),
	'Cost', 1500,
	'Slot', "Head",
	'PenetrationClass', 3,
	'DamageReduction', 45,
	'AdditionalReduction', 40,
	'ProtectedBodyParts', set( "Head", "Neck" ),
}),
PlaceObj('ModItemInventoryItemCompositeDef', {
	'Group', "Ammo",
	'Id', "_556_Sabre",
	'object_class', "Ammo",
	'Icon', "UI/Icons/Items/556_nato_bullets_basic",
	'SubIcon', "UI/Icons/Weapons/balanced",
	'DisplayName', T(312449656517, --[[ModItemInventoryItemCompositeDef _556_Sabre DisplayName]] "5.56 mm Sabre"),
	'colorStyle', "AmmoBasicColor",
	'Description', T(474565333375, --[[ModItemInventoryItemCompositeDef _556_Sabre Description]] "5.56 Ammo for Assault Rifles, SMGs, and Machine Guns."),
	'AdditionalHint', T(707465557230, --[[ModItemInventoryItemCompositeDef _556_Sabre AdditionalHint]] "<bullet_point> High Crit chance\n<bullet_point> Hit enemies are <em>Exposed</em> and lose the benefits of Cover\n<bullet_point> Inflicts <em>Bleeding</em>"),
	'MaxStacks', 9999,
	'Caliber', "556",
	'Modifications', {
		PlaceObj('CaliberModification', {
			mod_add = 50,
			target_prop = "CritChance",
		}),
		PlaceObj('CaliberModification', {
			mod_add = 1,
			target_prop = "PenetrationClass",
		}),
	},
	'AppliedEffects', {
		"Exposed",
		"Bleeding",
	},
}),
PlaceObj('ModItemInventoryItemCompositeDef', {
	'Group', "Ammo",
	'Id', "_9mm_Sabre",
	'object_class', "Ammo",
	'Icon', "UI/Icons/Items/9mm_bullets_tracer",
	'SubIcon', "UI/Icons/Weapons/balanced",
	'DisplayName', T(729120690447, --[[ModItemInventoryItemCompositeDef _9mm_Sabre DisplayName]] "9mm Sabre"),
	'DisplayNamePlural', T(223093350651, --[[ModItemInventoryItemCompositeDef _9mm_Sabre DisplayNamePlural]] "9mm Sabre"),
	'colorStyle', "AmmoHPColor",
	'Description', T(917859138490, --[[ModItemInventoryItemCompositeDef _9mm_Sabre Description]] "9 mm ammo for Handguns and SMGs."),
	'AdditionalHint', T(359901535743, --[[ModItemInventoryItemCompositeDef _9mm_Sabre AdditionalHint]] "<bullet_point> High Crit chance\n<bullet_point> Hit enemies are <em>Exposed</em> and lose the benefits of Cover\n<bullet_point> Inflicts <em>Bleeding</em>"),
	'MaxStacks', 9999,
	'Caliber', "9mm",
	'Modifications', {
		PlaceObj('CaliberModification', {
			mod_add = 50,
			target_prop = "CritChance",
		}),
		PlaceObj('CaliberModification', {
			mod_add = 1,
			target_prop = "PenetrationClass",
		}),
	},
	'AppliedEffects', {
		"Exposed",
		"Bleeding",
	},
}),
PlaceObj('ModItemInventoryItemCompositeDef', {
	'Group', "Ammo",
	'Id', "_556_PlusP",
	'object_class', "Ammo",
	'Icon', "UI/Icons/Items/556_nato_bullets_match",
	'SubIcon', "UI/Icons/Weapons/balanced",
	'DisplayName', T(307818297147, --[[ModItemInventoryItemCompositeDef _556_PlusP DisplayName]] "5.56 mm Match +P"),
	'colorStyle', "AmmoMatchColor",
	'Description', T(178223243989, --[[ModItemInventoryItemCompositeDef _556_PlusP Description]] "5.56 Ammo for Assault Rifles, SMGs, and Machine Guns."),
	'AdditionalHint', T(499283541722, --[[ModItemInventoryItemCompositeDef _556_PlusP AdditionalHint]] "<bullet_point> Increased bonus from Aiming\n<bullet_point> Hit enemies are <em>Exposed</em> and lose the benefits of Cover"),
	'MaxStacks', 9999,
	'Caliber', "556",
	'Modifications', {
		PlaceObj('CaliberModification', {
			mod_add = 2,
			target_prop = "AimAccuracy",
		}),
	},
	'AppliedEffects', {
		"Exposed",
	},
}),
PlaceObj('ModItemInventoryItemCompositeDef', {
	'Group', "Ammo",
	'Id', "_556_Phosphor",
	'object_class', "Ammo",
	'Icon', "UI/Icons/Items/556_nato_bullets_armor_piercing",
	'SubIcon', "UI/Icons/Weapons/balanced",
	'DisplayName', T(716265170656, --[[ModItemInventoryItemCompositeDef _556_Phosphor DisplayName]] "5.56 mm WP"),
	'colorStyle', "AmmoTracerColor",
	'Description', T(147051360725, --[[ModItemInventoryItemCompositeDef _556_Phosphor Description]] "5.56 Ammo for Assault Rifles, SMGs, and Machine Guns."),
	'AdditionalHint', T(976601230393, --[[ModItemInventoryItemCompositeDef _556_Phosphor AdditionalHint]] "<bullet_point> Hit enemies are <em>Exposed</em> and lose the benefits of Cover\n<bullet_point> Inflicts <em>Burning</em>\n<bullet_point> Inflicts <em>Bleeding</em>"),
	'MaxStacks', 9999,
	'Caliber', "556",
	'Modifications', {},
	'AppliedEffects', {
		"Exposed",
		"Burning",
		"Bleeding",
	},
}),
PlaceObj('ModItemSectorOperation', {
	Custom = false,
	GetOperationCost = function (self, merc, profession, idx)
		return SectorOperations["CraftCommonBase"].GetOperationCost(self, merc,profession, idx)
	end,
	GetSectorSlots = function (self, prof, sector)
		return 1
	end,
	HasOperation = function (self, sector)
		return sector.Port
	end,
	IsEnabled = function (self, sector)
		return SectorOperations["CraftCommonBase"].IsEnabled(self, sector)
	end,
	OnRemoveOperation = function (self, merc)
		SectorOperations["CraftCommonBase"].OnRemoveOperation(self, merc)
	end,
	OnSetOperation = function (self, merc, arg)
		SectorOperations["CraftCommonBase"].OnSetOperation(self, merc, arg)
	end,
	Parameters = {
		PlaceObj('PresetParamNumber', {
			'Name', "PerTickProgress",
			'Value', 250,
			'Tag', "<PerTickProgress>",
		}),
		PlaceObj('PresetParamNumber', {
			'Name', "MoneyCostBase",
			'Value', 250,
			'Tag', "<MoneyCostBase>",
		}),
	},
	Professions = {
		PlaceObj('SectorOperationProfession', {
			'id', "Trader",
			'display_name', T(688045936161, --[[ModItemSectorOperation CraftExplosives display_name]] "Trader"),
			'display_name_all_caps', T(795298995923, --[[ModItemSectorOperation CraftExplosives display_name_all_caps]] "TRADER"),
			'display_name_plural', T(199998290735, --[[ModItemSectorOperation CraftExplosives display_name_plural]] "Traders"),
			'display_name_plural_all_caps', T(821809069085, --[[ModItemSectorOperation CraftExplosives display_name_plural_all_caps]] "TRADERS"),
		}),
	},
	ProgressCompleteThreshold = function (self, merc, sector, prediction)
		return SectorOperations["CraftCommonBase"].ProgressCompleteThreshold(self, merc,sector, prediction)
	end,
	ProgressCurrent = function (self, merc, sector, prediction)
		return SectorOperations["CraftCommonBase"].ProgressCurrent(self, merc,sector, prediction)
	end,
	ProgressPerTick = function (self, merc, prediction)
		return SectorOperations["CraftCommonBase"].ProgressPerTick(self, merc, prediction)
	end,
	RequiredResources = {
		"Money",
		"Parts",
	},
	SectorOperationStats = function (self, sector, check_only)
		return SectorOperations["CraftCommonBase"].SectorOperationStats(self, sector, check_only)
	end,
	SortKey = 56,
	Tick = function (self, merc)
		return SectorOperations["CraftCommonBase"].Tick(self, merc)
	end,
	bonus_perks = {
		PlaceObj('SectorOperationBonusPerk', {
			'perk', "Negotiator",
			'bonus', 50,
		}),
		PlaceObj('SectorOperationBonusPerk', {
			'perk', "Scoundrel",
			'bonus', 25,
		}),
	},
	description = T(490092255109, --[[ModItemSectorOperation CraftExplosives description]] "Attain equipment by using diamonds to entice smugglers. High <color EmStyle>Leadership</color> stat will increase buying speed. "),
	display_name = T(401582506116, --[[ModItemSectorOperation CraftExplosives display_name]] "Contact Smugglers"),
	icon = "Mod/Dwo4JJm/icons/smugglesmall.png",
	id = "CraftExplosives",
	image = "Mod/Dwo4JJm/icons/smuggleicon.png",
	min_requirement_stat = "Leadership",
	min_requirement_stat_value = 15,
	related_stat = "Leadership",
	short_name = T(560942645178, --[[ModItemSectorOperation CraftExplosives short_name]] "Smuggle"),
	target_contribution = 750,
}),
}
