return PlaceObj('ModDef', {
	'title', "Contact Smugglers",
	'description', "Allows you to use tiny diamonds and diamond briefcases to purchase weapons, components and armor.",
	'image', "Mod/Dwo4JJm/icons/smuggleicon.png",
	'last_changes', "Did a bunch of shit",
	'id', "Dwo4JJm",
	'author', "I_van",
	'version_major', 1,
	'version_minor', 6,
	'version', 154,
	'lua_revision', 233360,
	'saved_with_revision', 340446,
	'code', {
		"Code/CraftOperationsRecipeDef.lua",
		"Code/RecipeDef.lua",
		"InventoryItem/crate_bereta92f.lua",
		"InventoryItem/crate_Microchip.lua",
		"InventoryItem/crate_peacemaker.lua",
		"InventoryItem/crate_coltanaconda.lua",
		"InventoryItem/crate_flaregun.lua",
		"InventoryItem/crate_deserteagle.lua",
		"InventoryItem/crate_glock18.lua",
		"InventoryItem/crate_Ak47.lua",
		"InventoryItem/crate_AK74.lua",
		"InventoryItem/crate_AR15.lua",
		"InventoryItem/crate_Famas.lua",
		"InventoryItem/crate_AUG.lua",
		"InventoryItem/crate_M16A2.lua",
		"InventoryItem/crate_G36.lua",
		"InventoryItem/crate_m14SAW.lua",
		"InventoryItem/crate_Galil.lua",
		"InventoryItem/crate_FNFAL.lua",
		"InventoryItem/crate_MGL.lua",
		"InventoryItem/crate_RPG7.lua",
		"InventoryItem/crate_mortarinventoryitem.lua",
		"InventoryItem/crate_40mmflashbang.lua",
		"InventoryItem/crate_40mmfrag.lua",
		"InventoryItem/crate_WarheadFrag.lua",
		"InventoryItem/crate_MortarShell_HE.lua",
		"InventoryItem/crate_MortarShell_Gas.lua",
		"InventoryItem/crate_MortarShell_Smoke.lua",
		"InventoryItem/crate_MG42.lua",
		"InventoryItem/crate_RPK74.lua",
		"InventoryItem/crate_FNMinimi.lua",
		"InventoryItem/crate_HK21.lua",
		"InventoryItem/crate_DragunovSVD.lua",
		"InventoryItem/crate_M24Sniper.lua",
		"InventoryItem/crate_PSG1.lua",
		"InventoryItem/crate_BarretM82.lua",
		"InventoryItem/crate_Uzi.lua",
		"InventoryItem/crate_MP5k.lua",
		"InventoryItem/crate_Mp5.lua",
		"InventoryItem/crate_AKSU.lua",
		"InventoryItem/crate_M4Commando.lua",
		"InventoryItem/crate_Auto5.lua",
		"InventoryItem/crate_M41Shotgun.lua",
		"InventoryItem/crate_AA12.lua",
		"InventoryItem/crate_Blackpowder.lua",
		"InventoryItem/crate_FragGrenade.lua",
		"InventoryItem/crate_HEGrenade.lua",
		"InventoryItem/crate_CamoLight.lua",
		"InventoryItem/crate_camomedium.lua",
		"InventoryItem/crate_gasmask.lua",
		"InventoryItem/crate_nightvisiongoggles.lua",
		"InventoryItem/crate_KevlarSet.lua",
		"InventoryItem/crate_KevlarSet_1.lua",
		"InventoryItem/crate_HeavySet.lua",
		"InventoryItem/crate_44cal.lua",
		"InventoryItem/crate_12gaugebuckshot.lua",
		"InventoryItem/crate_50bmg.lua",
		"InventoryItem/crate_556.lua",
		"InventoryItem/crate_556_sabre.lua",
		"InventoryItem/crate_556_p.lua",
		"InventoryItem/crate_556_phosphor.lua",
		"InventoryItem/crate_762nato.lua",
		"InventoryItem/crate_762WP.lua",
		"InventoryItem/crate_9mm.lua",
		"InventoryItem/crate_Explosives.lua",
		"InventoryItem/crate_RemoteDets.lua",
		"InventoryItem/crate_ProxyDets.lua",
		"InventoryItem/crate_TimeDets.lua",
		"InventoryItem/crate_plates.lua",
		"InventoryItem/crate_lockpick.lua",
		"InventoryItem/crate_firstaidkit.lua",
		"InventoryItem/crate_machete.lua",
		"InventoryItem/crate_Winchester.lua",
		"InventoryItem/crate_knife.lua",
		"InventoryItem/Armo_Spec_Ops_Vest_1.lua",
		"InventoryItem/Armor_Spec_Ops_leggings_1.lua",
		"InventoryItem/Armor_Spec_Ops_Helmet_1.lua",
		"InventoryItem/_556_Sabre.lua",
		"InventoryItem/_556_PlusP.lua",
		"InventoryItem/_556_Phosphor.lua",
	},
	'saved', 1696103413,
	'code_hash', 6643143809225782623,
	'steam_id', "3011061964",
})