-- ========== GENERATED BY CraftOperationsRecipeDef Editor DO NOT EDIT MANUALLY! ==========

PlaceObj('CraftOperationsRecipeDef', {
	CraftTime = 1,
	Ingredients = {
		PlaceObj('RecipeIngredient', {
			'item', "Parts",
			'amount', 15,
		}),
		PlaceObj('RecipeIngredient', {
			'item', "TNT",
		}),
	},
	ResultItem = PlaceObj('RecipeIngredient', {
		'item', "_40mmFlashbangGrenade",
		'amount', 5,
	}),
	group = "Ammo",
	id = "40mmFlash",
})

PlaceObj('CraftOperationsRecipeDef', {
	CraftTime = 1,
	Ingredients = {
		PlaceObj('RecipeIngredient', {
			'item', "Parts",
			'amount', 15,
		}),
		PlaceObj('RecipeIngredient', {
			'item', "C4",
		}),
	},
	ResultItem = PlaceObj('RecipeIngredient', {
		'item', "_40mmFragGrenade",
		'amount', 5,
	}),
	group = "Ammo",
	id = "40mmFrag",
})

PlaceObj('CraftOperationsRecipeDef', {
	CraftTime = 1,
	Ingredients = {
		PlaceObj('RecipeIngredient', {
			'item', "Parts",
			'amount', 35,
		}),
		PlaceObj('RecipeIngredient', {
			'item', "TNT",
			'amount', 3,
		}),
	},
	RequiredCrafter = "Barry",
	ResultItem = PlaceObj('RecipeIngredient', {
		'item', "ShapedCharge",
		'amount', 3,
	}),
	group = "Ammo",
	id = "Barry_ShapedCharge",
})

PlaceObj('CraftOperationsRecipeDef', {
	CraftTime = 1,
	Ingredients = {
		PlaceObj('RecipeIngredient', {
			'item', "Parts",
			'amount', 10,
		}),
		PlaceObj('RecipeIngredient', {
			'item', "BlackPowder",
			'amount', 3,
		}),
	},
	ResultItem = PlaceObj('RecipeIngredient', {
		'item', "ConcussiveGrenade",
		'amount', 5,
	}),
	group = "Ammo",
	id = "ConcussiveGrenade",
})

PlaceObj('CraftOperationsRecipeDef', {
	CraftTime = 1,
	Ingredients = {
		PlaceObj('RecipeIngredient', {
			'item', "Parts",
			'amount', 20,
		}),
		PlaceObj('RecipeIngredient', {
			'item', "TNT",
		}),
	},
	ResultItem = PlaceObj('RecipeIngredient', {
		'item', "FragGrenade",
		'amount', 5,
	}),
	group = "Ammo",
	id = "FragGrenade",
})

PlaceObj('CraftOperationsRecipeDef', {
	CraftTime = 1,
	Ingredients = {
		PlaceObj('RecipeIngredient', {
			'item', "Parts",
			'amount', 20,
		}),
		PlaceObj('RecipeIngredient', {
			'item', "TNT",
			'amount', 2,
		}),
	},
	ResultItem = PlaceObj('RecipeIngredient', {
		'item', "HE_Grenade",
		'amount', 5,
	}),
	group = "Ammo",
	id = "HE_Grenade",
})

PlaceObj('CraftOperationsRecipeDef', {
	CraftTime = 1,
	Ingredients = {
		PlaceObj('RecipeIngredient', {
			'item', "Parts",
			'amount', 10,
		}),
		PlaceObj('RecipeIngredient', {
			'item', "BlackPowder",
		}),
	},
	ResultItem = PlaceObj('RecipeIngredient', {
		'item', "Molotov",
		'amount', 5,
	}),
	group = "Ammo",
	id = "Molotov",
})

PlaceObj('CraftOperationsRecipeDef', {
	CraftTime = 1,
	Ingredients = {
		PlaceObj('RecipeIngredient', {
			'item', "Parts",
			'amount', 20,
		}),
		PlaceObj('RecipeIngredient', {
			'item', "Meds",
			'amount', 20,
		}),
		PlaceObj('RecipeIngredient', {
			'item', "C4",
		}),
	},
	ResultItem = PlaceObj('RecipeIngredient', {
		'item', "MortarShell_Gas",
		'amount', 5,
	}),
	group = "Ammo",
	id = "MortarShell_Gas",
})

PlaceObj('CraftOperationsRecipeDef', {
	CraftTime = 1,
	Ingredients = {
		PlaceObj('RecipeIngredient', {
			'item', "Parts",
			'amount', 30,
		}),
		PlaceObj('RecipeIngredient', {
			'item', "C4",
		}),
	},
	ResultItem = PlaceObj('RecipeIngredient', {
		'item', "MortarShell_Smoke",
		'amount', 5,
	}),
	group = "Ammo",
	id = "MortarShell_HE",
})

PlaceObj('CraftOperationsRecipeDef', {
	CraftTime = 1,
	Ingredients = {
		PlaceObj('RecipeIngredient', {
			'item', "Parts",
			'amount', 20,
		}),
		PlaceObj('RecipeIngredient', {
			'item', "Meds",
			'amount', 10,
		}),
		PlaceObj('RecipeIngredient', {
			'item', "TNT",
		}),
	},
	ResultItem = PlaceObj('RecipeIngredient', {
		'item', "MortarShell_Smoke",
		'amount', 5,
	}),
	group = "Ammo",
	id = "MortarShell_Smoke",
})

PlaceObj('CraftOperationsRecipeDef', {
	CraftTime = 1,
	Ingredients = {
		PlaceObj('RecipeIngredient', {
			'item', "Parts",
			'amount', 2,
		}),
		PlaceObj('RecipeIngredient', {
			'item', "BlackPowder",
		}),
	},
	ResultItem = PlaceObj('RecipeIngredient', {
		'item', "PipeBomb",
	}),
	group = "Ammo",
	id = "PipeBomb",
})

PlaceObj('CraftOperationsRecipeDef', {
	CraftTime = 1,
	Ingredients = {
		PlaceObj('RecipeIngredient', {
			'item', "Parts",
			'amount', 10,
		}),
		PlaceObj('RecipeIngredient', {
			'item', "Meds",
			'amount', 5,
		}),
		PlaceObj('RecipeIngredient', {
			'item', "BlackPowder",
		}),
	},
	ResultItem = PlaceObj('RecipeIngredient', {
		'item', "SmokeGrenade",
		'amount', 5,
	}),
	group = "Ammo",
	id = "SmokeGrenade",
})

PlaceObj('CraftOperationsRecipeDef', {
	CraftTime = 1,
	Ingredients = {
		PlaceObj('RecipeIngredient', {
			'item', "Parts",
			'amount', 10,
		}),
		PlaceObj('RecipeIngredient', {
			'item', "Meds",
			'amount', 15,
		}),
		PlaceObj('RecipeIngredient', {
			'item', "TNT",
		}),
	},
	ResultItem = PlaceObj('RecipeIngredient', {
		'item', "TearGasGrenade",
		'amount', 5,
	}),
	group = "Ammo",
	id = "TearGasGrenade",
})

PlaceObj('CraftOperationsRecipeDef', {
	CraftTime = 1,
	Ingredients = {
		PlaceObj('RecipeIngredient', {
			'item', "Parts",
			'amount', 10,
		}),
	},
	ResultItem = PlaceObj('RecipeIngredient', {
		'item', "crate_bereta92f",
		'amount', 1,
	}),
	group = "Explosives",
	id = "bereta92f_purchase",
})

PlaceObj('CraftOperationsRecipeDef', {
	CraftTime = 1,
	Ingredients = {
		PlaceObj('RecipeIngredient', {
			'item', "Parts",
			'amount', 10,
		}),
	},
	ResultItem = PlaceObj('RecipeIngredient', {
		'item', "crate_Microchip",
		'amount', 1,
	}),
	group = "Explosives",
	id = "crateMicrochip_purchase",
})

PlaceObj('CraftOperationsRecipeDef', {
	CraftTime = 1,
	Ingredients = {
		PlaceObj('RecipeIngredient', {
			'item', "Parts",
			'amount', 10,
		}),
	},
	ResultItem = PlaceObj('RecipeIngredient', {
		'item', "crate_peacemaker",
		'amount', 1,
	}),
	group = "Explosives",
	id = "peacemaker_purchase",
})

PlaceObj('CraftOperationsRecipeDef', {
	CraftTime = 1,
	Ingredients = {
		PlaceObj('RecipeIngredient', {
			'item', "Parts",
			'amount', 10,
		}),
	},
	ResultItem = PlaceObj('RecipeIngredient', {
		'item', "crate_flaregun",
		'amount', 1,
	}),
	group = "Explosives",
	id = "flaregun_purchase",
})

PlaceObj('CraftOperationsRecipeDef', {
	CraftTime = 1,
	Ingredients = {
		PlaceObj('RecipeIngredient', {
			'item', "Parts",
			'amount', 40,
		}),
	},
	ResultItem = PlaceObj('RecipeIngredient', {
		'item', "crate_coltanaconda",
		'amount', 1,
	}),
	group = "Explosives",
	id = "coltanaconda_purchase",
})

PlaceObj('CraftOperationsRecipeDef', {
	CraftTime = 1,
	Ingredients = {
		PlaceObj('RecipeIngredient', {
			'item', "Parts",
			'amount', 60,
		}),
	},
	ResultItem = PlaceObj('RecipeIngredient', {
		'item', "crate_deserteagle",
		'amount', 1,
	}),
	group = "Explosives",
	id = "deserteagle_purchase",
})

PlaceObj('CraftOperationsRecipeDef', {
	CraftTime = 1,
	Ingredients = {
		PlaceObj('RecipeIngredient', {
			'item', "Parts",
			'amount', 60,
		}),
	},
	ResultItem = PlaceObj('RecipeIngredient', {
		'item', "crate_glock18",
		'amount', 1,
	}),
	group = "Explosives",
	id = "glock18_purchase",
})

PlaceObj('CraftOperationsRecipeDef', {
	CraftTime = 1,
	Ingredients = {
		PlaceObj('RecipeIngredient', {
			'item', "Parts",
			'amount', 20,
		}),
	},
	ResultItem = PlaceObj('RecipeIngredient', {
		'item', "crate_Ak47",
		'amount', 1,
	}),
	group = "Explosives",
	id = "ak47_purchase",
})

PlaceObj('CraftOperationsRecipeDef', {
	CraftTime = 1,
	Ingredients = {
		PlaceObj('RecipeIngredient', {
			'item', "Parts",
			'amount', 300,
		}),
	},
	ResultItem = PlaceObj('RecipeIngredient', {
		'item', "crate_AK74",
		'amount', 1,
	}),
	group = "Explosives",
	id = "ak74_purchase",
})

PlaceObj('CraftOperationsRecipeDef', {
	CraftTime = 1,
	Ingredients = {
		PlaceObj('RecipeIngredient', {
			'item', "Parts",
			'amount', 220,
		}),
	},
	ResultItem = PlaceObj('RecipeIngredient', {
		'item', "crate_AR15",
		'amount', 1,
	}),
	group = "Explosives",
	id = "ar15_purchase",
})

PlaceObj('CraftOperationsRecipeDef', {
	CraftTime = 1,
	Ingredients = {
		PlaceObj('RecipeIngredient', {
			'item', "Parts",
			'amount', 40,
		}),
	},
	ResultItem = PlaceObj('RecipeIngredient', {
		'item', "crate_Famas",
		'amount', 1,
	}),
	group = "Explosives",
	id = "famas_purchase",
})

PlaceObj('CraftOperationsRecipeDef', {
	CraftTime = 1,
	Ingredients = {
		PlaceObj('RecipeIngredient', {
			'item', "Parts",
			'amount', 130,
		}),
	},
	ResultItem = PlaceObj('RecipeIngredient', {
		'item', "crate_AUG",
		'amount', 1,
	}),
	group = "Explosives",
	id = "aug_purchase",
})

PlaceObj('CraftOperationsRecipeDef', {
	CraftTime = 1,
	Ingredients = {
		PlaceObj('RecipeIngredient', {
			'item', "Parts",
			'amount', 70,
		}),
	},
	ResultItem = PlaceObj('RecipeIngredient', {
		'item', "crate_M16A2",
		'amount', 1,
	}),
	group = "Explosives",
	id = "m16a2_purchase",
})

PlaceObj('CraftOperationsRecipeDef', {
	CraftTime = 1,
	Ingredients = {
		PlaceObj('RecipeIngredient', {
			'item', "Parts",
			'amount', 230,
		}),
	},
	ResultItem = PlaceObj('RecipeIngredient', {
		'item', "crate_G36",
		'amount', 1,
	}),
	group = "Explosives",
	id = "g36_purchase",
})

PlaceObj('CraftOperationsRecipeDef', {
	CraftTime = 1,
	Ingredients = {
		PlaceObj('RecipeIngredient', {
			'item', "Parts",
			'amount', 40,
		}),
	},
	ResultItem = PlaceObj('RecipeIngredient', {
		'item', "crate_m14SAW",
		'amount', 1,
	}),
	group = "Explosives",
	id = "m14saw_purchase",
})

PlaceObj('CraftOperationsRecipeDef', {
	CraftTime = 1,
	Ingredients = {
		PlaceObj('RecipeIngredient', {
			'item', "Parts",
			'amount', 260,
		}),
	},
	ResultItem = PlaceObj('RecipeIngredient', {
		'item', "crate_Galil",
		'amount', 1,
	}),
	group = "Explosives",
	id = "galil_purchase",
})

PlaceObj('CraftOperationsRecipeDef', {
	CraftTime = 1,
	Ingredients = {
		PlaceObj('RecipeIngredient', {
			'item', "Parts",
			'amount', 100,
		}),
	},
	ResultItem = PlaceObj('RecipeIngredient', {
		'item', "crate_FNFAL",
		'amount', 1,
	}),
	group = "Explosives",
	id = "FNFAL_purchase",
})

PlaceObj('CraftOperationsRecipeDef', {
	CraftTime = 1,
	Ingredients = {
		PlaceObj('RecipeIngredient', {
			'item', "Parts",
			'amount', 250,
		}),
	},
	ResultItem = PlaceObj('RecipeIngredient', {
		'item', "crate_MGL",
		'amount', 1,
	}),
	group = "Explosives",
	id = "MGL_purchase",
})

PlaceObj('CraftOperationsRecipeDef', {
	CraftTime = 1,
	Ingredients = {
		PlaceObj('RecipeIngredient', {
			'item', "Parts",
			'amount', 130,
		}),
	},
	ResultItem = PlaceObj('RecipeIngredient', {
		'item', "crate_RPG7",
		'amount', 1,
	}),
	group = "Explosives",
	id = "RPG7_purchase",
})

PlaceObj('CraftOperationsRecipeDef', {
	CraftTime = 1,
	Ingredients = {
		PlaceObj('RecipeIngredient', {
			'item', "Parts",
			'amount', 250,
		}),
	},
	ResultItem = PlaceObj('RecipeIngredient', {
		'item', "crate_mortarinventoryitem",
		'amount', 1,
	}),
	group = "Explosives",
	id = "mortarinventoryitem_purchase",
})

PlaceObj('CraftOperationsRecipeDef', {
	CraftTime = 1,
	Ingredients = {
		PlaceObj('RecipeIngredient', {
			'item', "Parts",
			'amount', 50,
		}),
	},
	ResultItem = PlaceObj('RecipeIngredient', {
		'item', "crate_MG42",
		'amount', 1,
	}),
	group = "Explosives",
	id = "mg42_purchase",
})

PlaceObj('CraftOperationsRecipeDef', {
	CraftTime = 1,
	Ingredients = {
		PlaceObj('RecipeIngredient', {
			'item', "Parts",
			'amount', 80,
		}),
	},
	ResultItem = PlaceObj('RecipeIngredient', {
		'item', "crate_RPK74",
		'amount', 1,
	}),
	group = "Explosives",
	id = "rpk74_purchase",
})

PlaceObj('CraftOperationsRecipeDef', {
	CraftTime = 1,
	Ingredients = {
		PlaceObj('RecipeIngredient', {
			'item', "Parts",
			'amount', 350,
		}),
	},
	ResultItem = PlaceObj('RecipeIngredient', {
		'item', "crate_FNMinimi",
		'amount', 1,
	}),
	group = "Explosives",
	id = "fnminimi_purchase",
})

PlaceObj('CraftOperationsRecipeDef', {
	CraftTime = 1,
	Ingredients = {
		PlaceObj('RecipeIngredient', {
			'item', "Parts",
			'amount', 350,
		}),
	},
	ResultItem = PlaceObj('RecipeIngredient', {
		'item', "crate_HK21",
		'amount', 1,
	}),
	group = "Explosives",
	id = "hk21_purchase",
})

PlaceObj('CraftOperationsRecipeDef', {
	CraftTime = 1,
	Ingredients = {
		PlaceObj('RecipeIngredient', {
			'item', "Parts",
			'amount', 60,
		}),
	},
	ResultItem = PlaceObj('RecipeIngredient', {
		'item', "crate_DragunovSVD",
		'amount', 1,
	}),
	group = "Explosives",
	id = "dragunovsvd_purchase",
})

PlaceObj('CraftOperationsRecipeDef', {
	CraftTime = 1,
	Ingredients = {
		PlaceObj('RecipeIngredient', {
			'item', "Parts",
			'amount', 250,
		}),
	},
	ResultItem = PlaceObj('RecipeIngredient', {
		'item', "crate_Winchester",
		'amount', 1,
	}),
	group = "Explosives",
	id = "winchester_purchase",
})

PlaceObj('CraftOperationsRecipeDef', {
	CraftTime = 1,
	Ingredients = {
		PlaceObj('RecipeIngredient', {
			'item', "Parts",
			'amount', 250,
		}),
	},
	ResultItem = PlaceObj('RecipeIngredient', {
		'item', "crate_M24Sniper",
		'amount', 1,
	}),
	group = "Explosives",
	id = "m24sniper_purchase",
})

PlaceObj('CraftOperationsRecipeDef', {
	CraftTime = 1,
	Ingredients = {
		PlaceObj('RecipeIngredient', {
			'item', "Parts",
			'amount', 230,
		}),
	},
	ResultItem = PlaceObj('RecipeIngredient', {
		'item', "crate_PSG1",
		'amount', 1,
	}),
	group = "Explosives",
	id = "psg1_purchase",
})

PlaceObj('CraftOperationsRecipeDef', {
	CraftTime = 1,
	Ingredients = {
		PlaceObj('RecipeIngredient', {
			'item', "Parts",
			'amount', 230,
		}),
	},
	ResultItem = PlaceObj('RecipeIngredient', {
		'item', "crate_BarretM82",
		'amount', 1,
	}),
	group = "Explosives",
	id = "barretm82_purchase",
})

PlaceObj('CraftOperationsRecipeDef', {
	CraftTime = 1,
	Ingredients = {
		PlaceObj('RecipeIngredient', {
			'item', "Parts",
			'amount', 20,
		}),
	},
	ResultItem = PlaceObj('RecipeIngredient', {
		'item', "crate_Uzi",
		'amount', 1,
	}),
	group = "Explosives",
	id = "uzi_purchase",
})

PlaceObj('CraftOperationsRecipeDef', {
	CraftTime = 1,
	Ingredients = {
		PlaceObj('RecipeIngredient', {
			'item', "Parts",
			'amount', 30,
		}),
	},
	ResultItem = PlaceObj('RecipeIngredient', {
		'item', "crate_MP5k",
		'amount', 1,
	}),
	group = "Explosives",
	id = "mp5k_purchase",
})

PlaceObj('CraftOperationsRecipeDef', {
	CraftTime = 1,
	Ingredients = {
		PlaceObj('RecipeIngredient', {
			'item', "Parts",
			'amount', 40,
		}),
	},
	ResultItem = PlaceObj('RecipeIngredient', {
		'item', "crate_Mp5",
		'amount', 1,
	}),
	group = "Explosives",
	id = "mp5_purchase",
})

PlaceObj('CraftOperationsRecipeDef', {
	CraftTime = 1,
	Ingredients = {
		PlaceObj('RecipeIngredient', {
			'item', "Parts",
			'amount', 250,
		}),
	},
	ResultItem = PlaceObj('RecipeIngredient', {
		'item', "crate_AKSU",
		'amount', 1,
	}),
	group = "Explosives",
	id = "aksu_purchase",
})

PlaceObj('CraftOperationsRecipeDef', {
	CraftTime = 1,
	Ingredients = {
		PlaceObj('RecipeIngredient', {
			'item', "Parts",
			'amount', 250,
		}),
	},
	ResultItem = PlaceObj('RecipeIngredient', {
		'item', "crate_M4Commando",
		'amount', 1,
	}),
	group = "Explosives",
	id = "m4commando_purchase",
})

PlaceObj('CraftOperationsRecipeDef', {
	CraftTime = 1,
	Ingredients = {
		PlaceObj('RecipeIngredient', {
			'item', "Parts",
			'amount', 40,
		}),
	},
	ResultItem = PlaceObj('RecipeIngredient', {
		'item', "crate_Auto5",
		'amount', 1,
	}),
	group = "Explosives",
	id = "auto5_purchase",
})

PlaceObj('CraftOperationsRecipeDef', {
	CraftTime = 1,
	Ingredients = {
		PlaceObj('RecipeIngredient', {
			'item', "Parts",
			'amount', 80,
		}),
	},
	ResultItem = PlaceObj('RecipeIngredient', {
		'item', "crate_M41Shotgun",
		'amount', 1,
	}),
	group = "Explosives",
	id = "m41shotgun_purchase",
})

PlaceObj('CraftOperationsRecipeDef', {
	CraftTime = 1,
	Ingredients = {
		PlaceObj('RecipeIngredient', {
			'item', "Parts",
			'amount', 230,
		}),
	},
	ResultItem = PlaceObj('RecipeIngredient', {
		'item', "crate_AA12",
		'amount', 1,
	}),
	group = "Explosives",
	id = "aa12_purchase",
})

PlaceObj('CraftOperationsRecipeDef', {
	CraftTime = 1,
	Ingredients = {
		PlaceObj('RecipeIngredient', {
			'item', "Parts",
			'amount', 40,
		}),
	},
	ResultItem = PlaceObj('RecipeIngredient', {
		'item', "crate_Blackpowder",
		'amount', 1,
	}),
	group = "Explosives",
	id = "powder_purchase",
})

PlaceObj('CraftOperationsRecipeDef', {
	CraftTime = 1,
	Ingredients = {
		PlaceObj('RecipeIngredient', {
			'item', "Parts",
			'amount', 40,
		}),
	},
	ResultItem = PlaceObj('RecipeIngredient', {
		'item', "crate_Explosives",
		'amount', 3,
	}),
	group = "Explosives",
	id = "explosives_purchase",
})

PlaceObj('CraftOperationsRecipeDef', {
	CraftTime = 1,
	Ingredients = {
		PlaceObj('RecipeIngredient', {
			'item', "Parts",
			'amount', 20,
		}),
	},
	ResultItem = PlaceObj('RecipeIngredient', {
		'item', "crate_RemoteDets",
		'amount', 3,
	}),
	group = "Explosives",
	id = "remotedets_purchase",
})

PlaceObj('CraftOperationsRecipeDef', {
	CraftTime = 1,
	Ingredients = {
		PlaceObj('RecipeIngredient', {
			'item', "Parts",
			'amount', 10,
		}),
	},
	ResultItem = PlaceObj('RecipeIngredient', {
		'item', "crate_ProxyDets",
		'amount', 3,
	}),
	group = "Explosives",
	id = "proxydets_purchase",
})

PlaceObj('CraftOperationsRecipeDef', {
	CraftTime = 1,
	Ingredients = {
		PlaceObj('RecipeIngredient', {
			'item', "Parts",
			'amount', 20,
		}),
	},
	ResultItem = PlaceObj('RecipeIngredient', {
		'item', "crate_TimeDets",
		'amount', 3,
	}),
	group = "Explosives",
	id = "timedets_purchase",
})

PlaceObj('CraftOperationsRecipeDef', {
	CraftTime = 1,
	Ingredients = {
		PlaceObj('RecipeIngredient', {
			'item', "Parts",
			'amount', 30,
		}),
	},
	ResultItem = PlaceObj('RecipeIngredient', {
		'item', "crate_HEGrenade",
		'amount', 3,
	}),
	group = "Explosives",
	id = "pineapple_purchase",
})

PlaceObj('CraftOperationsRecipeDef', {
	CraftTime = 1,
	Ingredients = {
		PlaceObj('RecipeIngredient', {
			'item', "Parts",
			'amount', 30,
		}),
	},
	ResultItem = PlaceObj('RecipeIngredient', {
		'item', "crate_FragGrenade",
		'amount', 3,
	}),
	group = "Explosives",
	id = "sticknade_purchase",
})

PlaceObj('CraftOperationsRecipeDef', {
	CraftTime = 1,
	Ingredients = {
		PlaceObj('RecipeIngredient', {
			'item', "Parts",
			'amount', 50,
		}),
	},
	ResultItem = PlaceObj('RecipeIngredient', {
		'item', "crate_40mmflashbang",
		'amount', 1,
	}),
	group = "Explosives",
	id = "40mmflash_purchase",
})

PlaceObj('CraftOperationsRecipeDef', {
	CraftTime = 1,
	Ingredients = {
		PlaceObj('RecipeIngredient', {
			'item', "Parts",
			'amount', 50,
		}),
	},
	ResultItem = PlaceObj('RecipeIngredient', {
		'item', "crate_40mmfrag",
		'amount', 1,
	}),
	group = "Explosives",
	id = "40mmfrag_purchase",
})

PlaceObj('CraftOperationsRecipeDef', {
	CraftTime = 1,
	Ingredients = {
		PlaceObj('RecipeIngredient', {
			'item', "Parts",
			'amount', 50,
		}),
	},
	ResultItem = PlaceObj('RecipeIngredient', {
		'item', "crate_WarheadFrag",
		'amount', 1,
	}),
	group = "Explosives",
	id = "rpgrocket_purchase",
})

PlaceObj('CraftOperationsRecipeDef', {
	CraftTime = 1,
	Ingredients = {
		PlaceObj('RecipeIngredient', {
			'item', "Parts",
			'amount', 70,
		}),
	},
	ResultItem = PlaceObj('RecipeIngredient', {
		'item', "crate_MortarShell_HE",
		'amount', 1,
	}),
	group = "Explosives",
	id = "shellHE_purchase",
})

PlaceObj('CraftOperationsRecipeDef', {
	CraftTime = 1,
	Ingredients = {
		PlaceObj('RecipeIngredient', {
			'item', "Parts",
			'amount', 70,
		}),
	},
	ResultItem = PlaceObj('RecipeIngredient', {
		'item', "crate_MortarShell_Gas",
		'amount', 1,
	}),
	group = "Explosives",
	id = "shellGas_purchase",
})

PlaceObj('CraftOperationsRecipeDef', {
	CraftTime = 1,
	Ingredients = {
		PlaceObj('RecipeIngredient', {
			'item', "Parts",
			'amount', 70,
		}),
	},
	ResultItem = PlaceObj('RecipeIngredient', {
		'item', "crate_MortarShell_Smoke",
		'amount', 1,
	}),
	group = "Explosives",
	id = "shellSmoke_purchase",
})

PlaceObj('CraftOperationsRecipeDef', {
	CraftTime = 1,
	Ingredients = {
		PlaceObj('RecipeIngredient', {
			'item', "Parts",
			'amount', 100,
		}),
	},
	ResultItem = PlaceObj('RecipeIngredient', {
		'item', "crate_CamoLight",
		'amount', 1,
	}),
	group = "Explosives",
	id = "camolight_purchase",
})

PlaceObj('CraftOperationsRecipeDef', {
	CraftTime = 1,
	Ingredients = {
		PlaceObj('RecipeIngredient', {
			'item', "Parts",
			'amount', 150,
		}),
	},
	ResultItem = PlaceObj('RecipeIngredient', {
		'item', "crate_camomedium",
		'amount', 1,
	}),
	group = "Explosives",
	id = "camomedium_purchase",
})

PlaceObj('CraftOperationsRecipeDef', {
	CraftTime = 1,
	Ingredients = {
		PlaceObj('RecipeIngredient', {
			'item', "Parts",
			'amount', 50,
		}),
	},
	ResultItem = PlaceObj('RecipeIngredient', {
		'item', "crate_gasmask",
		'amount', 1,
	}),
	group = "Explosives",
	id = "gasmask_purchase",
})

PlaceObj('CraftOperationsRecipeDef', {
	CraftTime = 1,
	Ingredients = {
		PlaceObj('RecipeIngredient', {
			'item', "Parts",
			'amount', 100,
		}),
	},
	ResultItem = PlaceObj('RecipeIngredient', {
		'item', "crate_nightvisiongoggles",
		'amount', 1,
	}),
	group = "Explosives",
	id = "nightvisiongoggles_purchase",
})

PlaceObj('CraftOperationsRecipeDef', {
	CraftTime = 1,
	Ingredients = {
		PlaceObj('RecipeIngredient', {
			'item', "Parts",
			'amount', 100,
		}),
	},
	ResultItem = PlaceObj('RecipeIngredient', {
		'item', "crate_KevlarSet",
		'amount', 1,
	}),
	group = "Explosives",
	id = "kevlarset_purchase",
})

PlaceObj('CraftOperationsRecipeDef', {
	CraftTime = 1,
	Ingredients = {
		PlaceObj('RecipeIngredient', {
			'item', "Parts",
			'amount', 150,
		}),
	},
	ResultItem = PlaceObj('RecipeIngredient', {
		'item', "crate_KevlarSet_1",
		'amount', 1,
	}),
	group = "Explosives",
	id = "kevlarset_purchase",
})

PlaceObj('CraftOperationsRecipeDef', {
	CraftTime = 1,
	Ingredients = {
		PlaceObj('RecipeIngredient', {
			'item', "Parts",
			'amount', 150,
		}),
	},
	ResultItem = PlaceObj('RecipeIngredient', {
		'item', "crate_HeavySet",
		'amount', 1,
	}),
	group = "Explosives",
	id = "heavyset_purchase",
})

PlaceObj('CraftOperationsRecipeDef', {
	CraftTime = 1,
	Ingredients = {
		PlaceObj('RecipeIngredient', {
			'item', "Parts",
			'amount', 10,
		}),
	},
	ResultItem = PlaceObj('RecipeIngredient', {
		'item', "crate_44cal",
		'amount', 1,
	}),
	group = "Explosives",
	id = "44cal_purchase",
})

PlaceObj('CraftOperationsRecipeDef', {
	CraftTime = 1,
	Ingredients = {
		PlaceObj('RecipeIngredient', {
			'item', "Parts",
			'amount', 10,
		}),
	},
	ResultItem = PlaceObj('RecipeIngredient', {
		'item', "crate_12gaugebuckshot",
		'amount', 1,
	}),
	group = "Explosives",
	id = "12gaugebuckshot_purchase",
})

PlaceObj('CraftOperationsRecipeDef', {
	CraftTime = 1,
	Ingredients = {
		PlaceObj('RecipeIngredient', {
			'item', "Parts",
			'amount', 40,
		}),
	},
	ResultItem = PlaceObj('RecipeIngredient', {
		'item', "crate_50bmg",
		'amount', 1,
	}),
	group = "Explosives",
	id = "50bmg_purchase",
})

PlaceObj('CraftOperationsRecipeDef', {
	CraftTime = 1,
	Ingredients = {
		PlaceObj('RecipeIngredient', {
			'item', "Parts",
			'amount', 20,
		}),
	},
	ResultItem = PlaceObj('RecipeIngredient', {
		'item', "crate_556",
		'amount', 1,
	}),
	group = "Explosives",
	id = "556_purchase",
})

PlaceObj('CraftOperationsRecipeDef', {
	CraftTime = 1,
	Ingredients = {
		PlaceObj('RecipeIngredient', {
			'item', "Parts",
			'amount', 20,
		}),
	},
	ResultItem = PlaceObj('RecipeIngredient', {
		'item', "crate_556_phosphor",
		'amount', 1,
	}),
	group = "Explosives",
	id = "crate_556_phosphor_purchase",
})


PlaceObj('CraftOperationsRecipeDef', {
	CraftTime = 1,
	Ingredients = {
		PlaceObj('RecipeIngredient', {
			'item', "Parts",
			'amount', 20,
		}),
	},
	ResultItem = PlaceObj('RecipeIngredient', {
		'item', "crate_556_p",
		'amount', 1,
	}),
	group = "Explosives",
	id = "crate_556_p_purchase",
})


PlaceObj('CraftOperationsRecipeDef', {
	CraftTime = 1,
	Ingredients = {
		PlaceObj('RecipeIngredient', {
			'item', "Parts",
			'amount', 20,
		}),
	},
	ResultItem = PlaceObj('RecipeIngredient', {
		'item', "crate_556_sabre",
		'amount', 1,
	}),
	group = "Explosives",
	id = "crate_556_sabre_purchase",
})


PlaceObj('CraftOperationsRecipeDef', {
	CraftTime = 1,
	Ingredients = {
		PlaceObj('RecipeIngredient', {
			'item', "Parts",
			'amount', 20,
		}),
	},
	ResultItem = PlaceObj('RecipeIngredient', {
		'item', "crate_762nato",
		'amount', 1,
	}),
	group = "Explosives",
	id = "762nato_purchase",
})

PlaceObj('CraftOperationsRecipeDef', {
	CraftTime = 1,
	Ingredients = {
		PlaceObj('RecipeIngredient', {
			'item', "Parts",
			'amount', 20,
		}),
	},
	ResultItem = PlaceObj('RecipeIngredient', {
		'item', "crate_762WP",
		'amount', 1,
	}),
	group = "Explosives",
	id = "762wp_purchase",
})

PlaceObj('CraftOperationsRecipeDef', {
	CraftTime = 1,
	Ingredients = {
		PlaceObj('RecipeIngredient', {
			'item', "Parts",
			'amount', 10,
		}),
	},
	ResultItem = PlaceObj('RecipeIngredient', {
		'item', "crate_9mm",
		'amount', 1,
	}),
	group = "Explosives",
	id = "9mm_purchase",
})

PlaceObj('CraftOperationsRecipeDef', {
	CraftTime = 1,
	Ingredients = {
		PlaceObj('RecipeIngredient', {
			'item', "Parts",
			'amount', 20,
		}),
	},
	ResultItem = PlaceObj('RecipeIngredient', {
		'item', "crate_plates",
		'amount', 1,
	}),
	group = "Explosives",
	id = "plates_purchase",
})

PlaceObj('CraftOperationsRecipeDef', {
	CraftTime = 1,
	Ingredients = {
		PlaceObj('RecipeIngredient', {
			'item', "Parts",
			'amount', 20,
		}),
	},
	ResultItem = PlaceObj('RecipeIngredient', {
		'item', "crate_lockpick",
		'amount', 1,
	}),
	group = "Explosives",
	id = "lockpick_purchase",
})

PlaceObj('CraftOperationsRecipeDef', {
	CraftTime = 1,
	Ingredients = {
		PlaceObj('RecipeIngredient', {
			'item', "Parts",
			'amount', 20,
		}),
	},
	ResultItem = PlaceObj('RecipeIngredient', {
		'item', "crate_firstaidkit",
		'amount', 1,
	}),
	group = "Explosives",
	id = "firstaidkit_purchase",
})

PlaceObj('CraftOperationsRecipeDef', {
	CraftTime = 1,
	Ingredients = {
		PlaceObj('RecipeIngredient', {
			'item', "Parts",
			'amount', 80,
		}),
	},
	ResultItem = PlaceObj('RecipeIngredient', {
		'item', "crate_machete",
		'amount', 1,
	}),
	group = "Explosives",
	id = "machete_purchase",
})

PlaceObj('CraftOperationsRecipeDef', {
	CraftTime = 1,
	Ingredients = {
		PlaceObj('RecipeIngredient', {
			'item', "Parts",
			'amount', 40,
		}),
	},
	ResultItem = PlaceObj('RecipeIngredient', {
		'item', "crate_knife",
		'amount', 1,
	}),
	group = "Explosives",
	id = "knife_purchase",
})