-- ========== GENERATED BY RecipeDef Editor DO NOT EDIT MANUALLY! ==========

PlaceObj('RecipeDef', {
	Difficulty = 3,
	MechanicalRoll = true,
	Ingredients = {
		PlaceObj('RecipeIngredient', {
			'item', "crate_Microchip",
			'amount', 1,
		}),
		PlaceObj('RecipeIngredient', {
			'item', "Parts",
			'amount', 1,
		}),
	},
	ResultItems = {
		PlaceObj('RecipeIngredient', {
			'item', "Microchip",
			'amount', 10,
		}),
		PlaceObj('RecipeIngredient', {
			'item', "FineSteelPipe",
			'amount', 10,
		}),
		PlaceObj('RecipeIngredient', {
			'item', "OpticalLens",
			'amount', 10,
		}),
		PlaceObj('RecipeIngredient', {
			'item', "Parts",
			'amount', 100,
		}),
	},
	group = "Explosives",
	id = "crate_Microchip_unbox",
	save_in = "Common",
})

PlaceObj('RecipeDef', {
	Difficulty = 3,
	MechanicalRoll = true,
	Ingredients = {
		PlaceObj('RecipeIngredient', {
			'item', "crate_bereta92f",
			'amount', 1,
		}),
		PlaceObj('RecipeIngredient', {
			'item', "Parts",
			'amount', 1,
		}),
	},
	ResultItems = {
		PlaceObj('RecipeIngredient', {
			'item', "Bereta92",
			'amount', 1,
		}),
		PlaceObj('RecipeIngredient', {
			'item', "Bereta92",
			'amount', 1,
		}),
	},
	group = "Explosives",
	id = "beretta_crate_unbox",
	save_in = "Common",
})

PlaceObj('RecipeDef', {
	Difficulty = 3,
	MechanicalRoll = true,
	Ingredients = {
		PlaceObj('RecipeIngredient', {
			'item', "crate_flaregun",
			'amount', 1,
		}),
		PlaceObj('RecipeIngredient', {
			'item', "Parts",
			'amount', 1,
		}),
	},
	ResultItems = {
		PlaceObj('RecipeIngredient', {
			'item', "FlareHandgun",
			'amount', 1,
		}),
		PlaceObj('RecipeIngredient', {
			'item', "FlareAmmo",
			'amount', 50,
		}),
	},
	group = "Explosives",
	id = "bereta92f_unbox",
	save_in = "Common",
})

PlaceObj('RecipeDef', {
	Difficulty = 3,
	MechanicalRoll = true,
	Ingredients = {
		PlaceObj('RecipeIngredient', {
			'item', "crate_peacemaker",
			'amount', 1,
		}),
		PlaceObj('RecipeIngredient', {
			'item', "Parts",
			'amount', 1,
		}),
	},
	ResultItems = {
		PlaceObj('RecipeIngredient', {
			'item', "ColtPeacemaker",
			'amount', 1,
		}),
		PlaceObj('RecipeIngredient', {
			'item', "ColtPeacemaker",
			'amount', 1,
		}),
	},
	group = "Explosives",
	id = "peacemaker_unbox",
	save_in = "Common",
})

PlaceObj('RecipeDef', {
	Difficulty = 3,
	MechanicalRoll = true,
	Ingredients = {
		PlaceObj('RecipeIngredient', {
			'item', "crate_coltanaconda",
			'amount', 1,
		}),
		PlaceObj('RecipeIngredient', {
			'item', "Parts",
			'amount', 1,
		}),
	},
	ResultItems = {
		PlaceObj('RecipeIngredient', {
			'item', "ColtAnaconda",
			'amount', 1,
		}),
	},
	group = "Explosives",
	id = "coltanaconda_unbox",
	save_in = "Common",
})

PlaceObj('RecipeDef', {
	Difficulty = 3,
	MechanicalRoll = true,
	Ingredients = {
		PlaceObj('RecipeIngredient', {
			'item', "crate_deserteagle",
			'amount', 1,
		}),
		PlaceObj('RecipeIngredient', {
			'item', "Parts",
			'amount', 1,
		}),
	},
	ResultItems = {
		PlaceObj('RecipeIngredient', {
			'item', "DesertEagle",
			'amount', 1,
		}),
	},
	group = "Explosives",
	id = "deserteagle_unbox",
	save_in = "Common",
})

PlaceObj('RecipeDef', {
	Difficulty = 3,
	MechanicalRoll = true,
	Ingredients = {
		PlaceObj('RecipeIngredient', {
			'item', "crate_glock18",
			'amount', 1,
		}),
		PlaceObj('RecipeIngredient', {
			'item', "Parts",
			'amount', 1,
		}),
	},
	ResultItems = {
		PlaceObj('RecipeIngredient', {
			'item', "Glock18",
			'amount', 1,
		}),
		PlaceObj('RecipeIngredient', {
			'item', "Glock18",
			'amount', 1,
		}),
	},
	group = "Explosives",
	id = "glock18_unbox",
	save_in = "Common",
})

PlaceObj('RecipeDef', {
	Difficulty = 3,
	MechanicalRoll = true,
	Ingredients = {
		PlaceObj('RecipeIngredient', {
			'item', "crate_Ak47",
			'amount', 1,
		}),
		PlaceObj('RecipeIngredient', {
			'item', "Parts",
			'amount', 1,
		}),
	},
	ResultItems = {
		PlaceObj('RecipeIngredient', {
			'item', "AK47",
			'amount', 1,
		}),
	},
	group = "Explosives",
	id = "ak47_unbox",
	save_in = "Common",
})

PlaceObj('RecipeDef', {
	Difficulty = 3,
	MechanicalRoll = true,
	Ingredients = {
		PlaceObj('RecipeIngredient', {
			'item', "crate_AK74",
			'amount', 1,
		}),
		PlaceObj('RecipeIngredient', {
			'item', "Parts",
			'amount', 1,
		}),
	},
	ResultItems = {
		PlaceObj('RecipeIngredient', {
			'item', "AK74",
			'amount', 1,
		}),
	},
	group = "Explosives",
	id = "ak74_unbox",
	save_in = "Common",
})

PlaceObj('RecipeDef', {
	Difficulty = 3,
	MechanicalRoll = true,
	Ingredients = {
		PlaceObj('RecipeIngredient', {
			'item', "crate_AR15",
			'amount', 1,
		}),
		PlaceObj('RecipeIngredient', {
			'item', "Parts",
			'amount', 1,
		}),
	},
	ResultItems = {
		PlaceObj('RecipeIngredient', {
			'item', "AR15",
			'amount', 1,
		}),
	},
	group = "Explosives",
	id = "ar15_unbox",
	save_in = "Common",
})

PlaceObj('RecipeDef', {
	Difficulty = 3,
	MechanicalRoll = true,
	Ingredients = {
		PlaceObj('RecipeIngredient', {
			'item', "crate_Famas",
			'amount', 1,
		}),
		PlaceObj('RecipeIngredient', {
			'item', "Parts",
			'amount', 1,
		}),
	},
	ResultItems = {
		PlaceObj('RecipeIngredient', {
			'item', "FAMAS",
			'amount', 1,
		}),
	},
	group = "Explosives",
	id = "famas_unbox",
	save_in = "Common",
})

PlaceObj('RecipeDef', {
	Difficulty = 3,
	MechanicalRoll = true,
	Ingredients = {
		PlaceObj('RecipeIngredient', {
			'item', "crate_AUG",
			'amount', 1,
		}),
		PlaceObj('RecipeIngredient', {
			'item', "Parts",
			'amount', 1,
		}),
	},
	ResultItems = {
		PlaceObj('RecipeIngredient', {
			'item', "AUG",
			'amount', 1,
		}),
	},
	group = "Explosives",
	id = "aug_unbox",
	save_in = "Common",
})

PlaceObj('RecipeDef', {
	Difficulty = 3,
	MechanicalRoll = true,
	Ingredients = {
		PlaceObj('RecipeIngredient', {
			'item', "crate_M16A2",
			'amount', 1,
		}),
		PlaceObj('RecipeIngredient', {
			'item', "Parts",
			'amount', 1,
		}),
	},
	ResultItems = {
		PlaceObj('RecipeIngredient', {
			'item', "M16A2",
			'amount', 1,
		}),
	},
	group = "Explosives",
	id = "m16a2_unbox",
	save_in = "Common",
})

PlaceObj('RecipeDef', {
	Difficulty = 3,
	MechanicalRoll = true,
	Ingredients = {
		PlaceObj('RecipeIngredient', {
			'item', "crate_G36",
			'amount', 1,
		}),
		PlaceObj('RecipeIngredient', {
			'item', "Parts",
			'amount', 1,
		}),
	},
	ResultItems = {
		PlaceObj('RecipeIngredient', {
			'item', "G36",
			'amount', 1,
		}),
	},
	group = "Explosives",
	id = "g36_unbox",
	save_in = "Common",
})

PlaceObj('RecipeDef', {
	Difficulty = 3,
	MechanicalRoll = true,
	Ingredients = {
		PlaceObj('RecipeIngredient', {
			'item', "crate_m14SAW",
			'amount', 1,
		}),
		PlaceObj('RecipeIngredient', {
			'item', "Parts",
			'amount', 1,
		}),
	},
	ResultItems = {
		PlaceObj('RecipeIngredient', {
			'item', "M14SAW",
			'amount', 1,
		}),

	},
	group = "Explosives",
	id = "m14saw_unbox",
	save_in = "Common",
})

PlaceObj('RecipeDef', {
	Difficulty = 3,
	MechanicalRoll = true,
	Ingredients = {
		PlaceObj('RecipeIngredient', {
			'item', "crate_Galil",
			'amount', 1,
		}),
		PlaceObj('RecipeIngredient', {
			'item', "Parts",
			'amount', 1,
		}),
	},
	ResultItems = {
		PlaceObj('RecipeIngredient', {
			'item', "Galil",
			'amount', 1,
		}),
	},
	group = "Explosives",
	id = "galil_unbox",
	save_in = "Common",
})

PlaceObj('RecipeDef', {
	Difficulty = 3,
	MechanicalRoll = true,
	Ingredients = {
		PlaceObj('RecipeIngredient', {
			'item', "crate_FNFAL",
			'amount', 1,
		}),
		PlaceObj('RecipeIngredient', {
			'item', "Parts",
			'amount', 1,
		}),
	},
	ResultItems = {
		PlaceObj('RecipeIngredient', {
			'item', "FNFAL",
			'amount', 1,
		}),
	},
	group = "Explosives",
	id = "fnfal_unbox",
	save_in = "Common",
})

PlaceObj('RecipeDef', {
	Difficulty = 3,
	MechanicalRoll = true,
	Ingredients = {
		PlaceObj('RecipeIngredient', {
			'item', "crate_MGL",
			'amount', 1,
		}),
		PlaceObj('RecipeIngredient', {
			'item', "Parts",
			'amount', 1,
		}),
	},
	ResultItems = {
		PlaceObj('RecipeIngredient', {
			'item', "MGL",
			'amount', 1,
		}),
	},
	group = "Explosives",
	id = "mgl_unbox",
	save_in = "Common",
})

PlaceObj('RecipeDef', {
	Difficulty = 3,
	MechanicalRoll = true,
	Ingredients = {
		PlaceObj('RecipeIngredient', {
			'item', "crate_RPG7",
			'amount', 1,
		}),
		PlaceObj('RecipeIngredient', {
			'item', "Parts",
			'amount', 1,
		}),
	},
	ResultItems = {
		PlaceObj('RecipeIngredient', {
			'item', "RPG7",
			'amount', 1,
		}),
	},
	group = "Explosives",
	id = "rpg7_unbox",
	save_in = "Common",
})

PlaceObj('RecipeDef', {
	Difficulty = 3,
	MechanicalRoll = true,
	Ingredients = {
		PlaceObj('RecipeIngredient', {
			'item', "crate_mortarinventoryitem",
			'amount', 1,
		}),
		PlaceObj('RecipeIngredient', {
			'item', "Parts",
			'amount', 1,
		}),
	},
	ResultItems = {
		PlaceObj('RecipeIngredient', {
			'item', "MortarInventoryItem",
			'amount', 1,
		}),
	},
	group = "Explosives",
	id = "mortar_unbox",
	save_in = "Common",
})

PlaceObj('RecipeDef', {
	Difficulty = 3,
	MechanicalRoll = true,
	Ingredients = {
		PlaceObj('RecipeIngredient', {
			'item', "crate_40mmflashbang",
			'amount', 1,
		}),
		PlaceObj('RecipeIngredient', {
			'item', "Parts",
			'amount', 1,
		}),
	},
	ResultItems = {
		PlaceObj('RecipeIngredient', {
			'item', "_40mmFlashbangGrenade",
			'amount', 90,
		}),
	},
	group = "Explosives",
	id = "flashbang_unbox",
	save_in = "Common",
})

PlaceObj('RecipeDef', {
	Difficulty = 3,
	MechanicalRoll = true,
	Ingredients = {
		PlaceObj('RecipeIngredient', {
			'item', "crate_40mmfrag",
			'amount', 1,
		}),
		PlaceObj('RecipeIngredient', {
			'item', "Parts",
			'amount', 1,
		}),
	},
	ResultItems = {
		PlaceObj('RecipeIngredient', {
			'item', "_40mmFragGrenade",
			'amount', 60,
		}),
	},
	group = "Explosives",
	id = "40mmfrag_unbox",
	save_in = "Common",
})

PlaceObj('RecipeDef', {
	Difficulty = 3,
	MechanicalRoll = true,
	Ingredients = {
		PlaceObj('RecipeIngredient', {
			'item', "crate_WarheadFrag",
			'amount', 1,
		}),
		PlaceObj('RecipeIngredient', {
			'item', "Parts",
			'amount', 1,
		}),
	},
	ResultItems = {
		PlaceObj('RecipeIngredient', {
			'item', "Warhead_Frag",
			'amount', 20,
		}),
	},
	group = "Explosives",
	id = "rpgrocket_unbox",
	save_in = "Common",
})

PlaceObj('RecipeDef', {
	Difficulty = 3,
	MechanicalRoll = true,
	Ingredients = {
		PlaceObj('RecipeIngredient', {
			'item', "crate_MortarShell_HE",
			'amount', 1,
		}),
		PlaceObj('RecipeIngredient', {
			'item', "Parts",
			'amount', 1,
		}),
	},
	ResultItems = {
		PlaceObj('RecipeIngredient', {
			'item', "MortarShell_HE",
			'amount', 20,
		}),
	},
	group = "Explosives",
	id = "shellHE_unbox",
	save_in = "Common",
})

PlaceObj('RecipeDef', {
	Difficulty = 3,
	MechanicalRoll = true,
	Ingredients = {
		PlaceObj('RecipeIngredient', {
			'item', "crate_MortarShell_Gas",
			'amount', 1,
		}),
		PlaceObj('RecipeIngredient', {
			'item', "Parts",
			'amount', 1,
		}),
	},
	ResultItems = {
		PlaceObj('RecipeIngredient', {
			'item', "MortarShell_Gas",
			'amount', 90,
		}),
	},
	group = "Explosives",
	id = "shellGas_unbox",
	save_in = "Common",
})

PlaceObj('RecipeDef', {
	Difficulty = 3,
	MechanicalRoll = true,
	Ingredients = {
		PlaceObj('RecipeIngredient', {
			'item', "crate_MortarShell_Smoke",
			'amount', 1,
		}),
		PlaceObj('RecipeIngredient', {
			'item', "Parts",
			'amount', 1,
		}),
	},
	ResultItems = {
		PlaceObj('RecipeIngredient', {
			'item', "MortarShell_Smoke",
			'amount', 90,
		}),
	},
	group = "Explosives",
	id = "shellSmoke_unbox",
	save_in = "Common",
})

PlaceObj('RecipeDef', {
	Difficulty = 3,
	MechanicalRoll = true,
	Ingredients = {
		PlaceObj('RecipeIngredient', {
			'item', "crate_MG42",
			'amount', 1,
		}),
		PlaceObj('RecipeIngredient', {
			'item', "Parts",
			'amount', 1,
		}),
	},
	ResultItems = {
		PlaceObj('RecipeIngredient', {
			'item', "MG42",
			'amount', 1,
		}),
	},
	group = "Explosives",
	id = "mg42_unbox",
	save_in = "Common",
})

PlaceObj('RecipeDef', {
	Difficulty = 3,
	MechanicalRoll = true,
	Ingredients = {
		PlaceObj('RecipeIngredient', {
			'item', "crate_RPK74",
			'amount', 1,
		}),
		PlaceObj('RecipeIngredient', {
			'item', "Parts",
			'amount', 1,
		}),
	},
	ResultItems = {
		PlaceObj('RecipeIngredient', {
			'item', "RPK74",
			'amount', 1,
		}),
	},
	group = "Explosives",
	id = "rpk74_unbox",
	save_in = "Common",
})

PlaceObj('RecipeDef', {
	Difficulty = 3,
	MechanicalRoll = true,
	Ingredients = {
		PlaceObj('RecipeIngredient', {
			'item', "crate_FNMinimi",
			'amount', 1,
		}),
		PlaceObj('RecipeIngredient', {
			'item', "Parts",
			'amount', 1,
		}),
	},
	ResultItems = {
		PlaceObj('RecipeIngredient', {
			'item', "FNMinimi",
			'amount', 1,
		}),
	},
	group = "Explosives",
	id = "fnminimi_unbox",
	save_in = "Common",
})

PlaceObj('RecipeDef', {
	Difficulty = 3,
	MechanicalRoll = true,
	Ingredients = {
		PlaceObj('RecipeIngredient', {
			'item', "crate_HK21",
			'amount', 1,
		}),
		PlaceObj('RecipeIngredient', {
			'item', "Parts",
			'amount', 1,
		}),
	},
	ResultItems = {
		PlaceObj('RecipeIngredient', {
			'item', "HK21",
			'amount', 1,
		}),
	},
	group = "Explosives",
	id = "hk21_unbox",
	save_in = "Common",
})

PlaceObj('RecipeDef', {
	Difficulty = 3,
	MechanicalRoll = true,
	Ingredients = {
		PlaceObj('RecipeIngredient', {
			'item', "crate_DragunovSVD",
			'amount', 1,
		}),
		PlaceObj('RecipeIngredient', {
			'item', "Parts",
			'amount', 1,
		}),
	},
	ResultItems = {
		PlaceObj('RecipeIngredient', {
			'item', "DragunovSVD",
			'amount', 1,
		}),
	},
	group = "Explosives",
	id = "dragunov_unbox",
	save_in = "Common",
})

PlaceObj('RecipeDef', {
	Difficulty = 3,
	MechanicalRoll = true,
	Ingredients = {
		PlaceObj('RecipeIngredient', {
			'item', "crate_Winchester",
			'amount', 1,
		}),
		PlaceObj('RecipeIngredient', {
			'item', "Parts",
			'amount', 1,
		}),
	},
	ResultItems = {
		PlaceObj('RecipeIngredient', {
			'item', "Winchester1894",
			'amount', 1,
		}),
	},
	group = "Explosives",
	id = "winchester_unbox",
	save_in = "Common",
})

PlaceObj('RecipeDef', {
	Difficulty = 3,
	MechanicalRoll = true,
	Ingredients = {
		PlaceObj('RecipeIngredient', {
			'item', "crate_M24Sniper",
			'amount', 1,
		}),
		PlaceObj('RecipeIngredient', {
			'item', "Parts",
			'amount', 1,
		}),
	},
	ResultItems = {
		PlaceObj('RecipeIngredient', {
			'item', "M24Sniper",
			'amount', 1,
		}),
	},
	group = "Explosives",
	id = "m24sniper_unbox",
	save_in = "Common",
})

PlaceObj('RecipeDef', {
	Difficulty = 3,
	MechanicalRoll = true,
	Ingredients = {
		PlaceObj('RecipeIngredient', {
			'item', "crate_PSG1",
			'amount', 1,
		}),
		PlaceObj('RecipeIngredient', {
			'item', "Parts",
			'amount', 1,
		}),
	},
	ResultItems = {
		PlaceObj('RecipeIngredient', {
			'item', "PSG1",
			'amount', 1,
		}),
	},
	group = "Explosives",
	id = "psg1_unbox",
	save_in = "Common",
})

PlaceObj('RecipeDef', {
	Difficulty = 3,
	MechanicalRoll = true,
	Ingredients = {
		PlaceObj('RecipeIngredient', {
			'item', "crate_BarretM82",
			'amount', 1,
		}),
		PlaceObj('RecipeIngredient', {
			'item', "Parts",
			'amount', 1,
		}),
	},
	ResultItems = {
		PlaceObj('RecipeIngredient', {
			'item', "BarretM82",
			'amount', 1,
		}),
	},
	group = "Explosives",
	id = "barret_unbox",
	save_in = "Common",
})

PlaceObj('RecipeDef', {
	Difficulty = 3,
	MechanicalRoll = true,
	Ingredients = {
		PlaceObj('RecipeIngredient', {
			'item', "crate_Uzi",
			'amount', 1,
		}),
		PlaceObj('RecipeIngredient', {
			'item', "Parts",
			'amount', 1,
		}),
	},
	ResultItems = {
		PlaceObj('RecipeIngredient', {
			'item', "UZI",
			'amount', 1,
		}),
		PlaceObj('RecipeIngredient', {
			'item', "SkillMag_Marksmanship",
			'amount', 1,
		}),
	},
	group = "Explosives",
	id = "uzi_unbox",
	save_in = "Common",
})

PlaceObj('RecipeDef', {
	Difficulty = 3,
	MechanicalRoll = true,
	Ingredients = {
		PlaceObj('RecipeIngredient', {
			'item', "crate_MP5k",
			'amount', 1,
		}),
		PlaceObj('RecipeIngredient', {
			'item', "Parts",
			'amount', 1,
		}),
	},
	ResultItems = {
		PlaceObj('RecipeIngredient', {
			'item', "MP5K",
			'amount', 1,
		}),
	},
	group = "Explosives",
	id = "mp5k_unbox",
	save_in = "Common",
})

PlaceObj('RecipeDef', {
	Difficulty = 3,
	MechanicalRoll = true,
	Ingredients = {
		PlaceObj('RecipeIngredient', {
			'item', "crate_Mp5",
			'amount', 1,
		}),
		PlaceObj('RecipeIngredient', {
			'item', "Parts",
			'amount', 1,
		}),
	},
	ResultItems = {
		PlaceObj('RecipeIngredient', {
			'item', "MP5",
			'amount', 1,
		}),
	},
	group = "Explosives",
	id = "mp5_unbox",
	save_in = "Common",
})

PlaceObj('RecipeDef', {
	Difficulty = 3,
	MechanicalRoll = true,
	Ingredients = {
		PlaceObj('RecipeIngredient', {
			'item', "crate_AKSU",
			'amount', 1,
		}),
		PlaceObj('RecipeIngredient', {
			'item', "Parts",
			'amount', 1,
		}),
	},
	ResultItems = {
		PlaceObj('RecipeIngredient', {
			'item', "AKSU",
			'amount', 1,
		}),
	},
	group = "Explosives",
	id = "aksu_unbox",
	save_in = "Common",
})

PlaceObj('RecipeDef', {
	Difficulty = 3,
	MechanicalRoll = true,
	Ingredients = {
		PlaceObj('RecipeIngredient', {
			'item', "crate_M4Commando",
			'amount', 1,
		}),
		PlaceObj('RecipeIngredient', {
			'item', "Parts",
			'amount', 1,
		}),
	},
	ResultItems = {
		PlaceObj('RecipeIngredient', {
			'item', "M4Commando",
			'amount', 1,
		}),
	},
	group = "Explosives",
	id = "m4commando_unbox",
	save_in = "Common",
})

PlaceObj('RecipeDef', {
	Difficulty = 3,
	MechanicalRoll = true,
	Ingredients = {
		PlaceObj('RecipeIngredient', {
			'item', "crate_Auto5",
			'amount', 1,
		}),
		PlaceObj('RecipeIngredient', {
			'item', "Parts",
			'amount', 1,
		}),
	},
	ResultItems = {
		PlaceObj('RecipeIngredient', {
			'item', "Auto5",
			'amount', 1,
		}),
	},
	group = "Explosives",
	id = "auto5_unbox",
	save_in = "Common",
})

PlaceObj('RecipeDef', {
	Difficulty = 3,
	MechanicalRoll = true,
	Ingredients = {
		PlaceObj('RecipeIngredient', {
			'item', "crate_M41Shotgun",
			'amount', 1,
		}),
		PlaceObj('RecipeIngredient', {
			'item', "Parts",
			'amount', 1,
		}),
	},
	ResultItems = {
		PlaceObj('RecipeIngredient', {
			'item', "M41Shotgun",
			'amount', 1,
		}),
	},
	group = "Explosives",
	id = "m41shotgun_unbox",
	save_in = "Common",
})

PlaceObj('RecipeDef', {
	Difficulty = 3,
	MechanicalRoll = true,
	Ingredients = {
		PlaceObj('RecipeIngredient', {
			'item', "crate_AA12",
			'amount', 1,
		}),
		PlaceObj('RecipeIngredient', {
			'item', "Parts",
			'amount', 1,
		}),
	},
	ResultItems = {
		PlaceObj('RecipeIngredient', {
			'item', "AA12",
			'amount', 1,
		}),
	},
	group = "Explosives",
	id = "aa12_unbox",
	save_in = "Common",
})

PlaceObj('RecipeDef', {
	Difficulty = 3,
	MechanicalRoll = true,
	Ingredients = {
		PlaceObj('RecipeIngredient', {
			'item', "crate_Blackpowder",
			'amount', 1,
		}),
		PlaceObj('RecipeIngredient', {
			'item', "Parts",
			'amount', 1,
		}),
	},
	ResultItems = {
		PlaceObj('RecipeIngredient', {
			'item', "BlackPowder",
			'amount', 90,
		}),
	},
	group = "Explosives",
	id = "blackpowder_unbox",
	save_in = "Common",
})

PlaceObj('RecipeDef', {
	Difficulty = 3,
	MechanicalRoll = true,
	Ingredients = {
		PlaceObj('RecipeIngredient', {
			'item', "crate_Blackpowder",
			'amount', 1,
		}),
		PlaceObj('RecipeIngredient', {
			'item', "Parts",
			'amount', 1,
		}),
	},
	ResultItems = {
		PlaceObj('RecipeIngredient', {
			'item', "BlackPowder",
			'amount', 90,
		}),
	},
	group = "Explosives",
	id = "blackpowder_unbox",
	save_in = "Common",
})

PlaceObj('RecipeDef', {
	Difficulty = 3,
	MechanicalRoll = true,
	Ingredients = {
		PlaceObj('RecipeIngredient', {
			'item', "crate_Explosives",
			'amount', 1,
		}),
		PlaceObj('RecipeIngredient', {
			'item', "Parts",
			'amount', 1,
		}),
	},
	ResultItems = {
		PlaceObj('RecipeIngredient', {
			'item', "C4",
			'amount', 20,
		}),
		PlaceObj('RecipeIngredient', {
			'item', "TNT",
			'amount', 30,
		}),
	},
	group = "Explosives",
	id = "explosives_unbox",
	save_in = "Common",
})

PlaceObj('RecipeDef', {
	Difficulty = 3,
	MechanicalRoll = true,
	Ingredients = {
		PlaceObj('RecipeIngredient', {
			'item', "crate_TimeDets",
			'amount', 1,
		}),
		PlaceObj('RecipeIngredient', {
			'item', "Parts",
			'amount', 1,
		}),
	},
	ResultItems = {
		PlaceObj('RecipeIngredient', {
			'item', "Combination_Detonator_Time",
			'amount', 30,
		}),
		PlaceObj('RecipeIngredient', {
			'item', "SkillMag_Explosives",
			'amount', 10,
		}),
	},
	group = "Explosives",
	id = "timer_unbox",
	save_in = "Common",
})

PlaceObj('RecipeDef', {
	Difficulty = 3,
	MechanicalRoll = true,
	Ingredients = {
		PlaceObj('RecipeIngredient', {
			'item', "crate_ProxyDets",
			'amount', 1,
		}),
		PlaceObj('RecipeIngredient', {
			'item', "Parts",
			'amount', 1,
		}),
	},
	ResultItems = {
		PlaceObj('RecipeIngredient', {
			'item', "Combination_Detonator_Proximity",
			'amount', 30,
		}),
		PlaceObj('RecipeIngredient', {
			'item', "SkillMag_Explosives",
			'amount', 10,
		}),
	},
	group = "Explosives",
	id = "proxy_unbox",
	save_in = "Common",
})

PlaceObj('RecipeDef', {
	Difficulty = 3,
	MechanicalRoll = true,
	Ingredients = {
		PlaceObj('RecipeIngredient', {
			'item', "crate_RemoteDets",
			'amount', 1,
		}),
		PlaceObj('RecipeIngredient', {
			'item', "Parts",
			'amount', 1,
		}),
	},
	ResultItems = {
		PlaceObj('RecipeIngredient', {
			'item', "Combination_Detonator_Remote",
			'amount', 30,
		}),
		PlaceObj('RecipeIngredient', {
			'item', "Detonator",
			'amount', 5,
		}),
	},
	group = "Explosives",
	id = "remote_unbox",
	save_in = "Common",
})

PlaceObj('RecipeDef', {
	Difficulty = 3,
	MechanicalRoll = true,
	Ingredients = {
		PlaceObj('RecipeIngredient', {
			'item', "crate_FragGrenade",
			'amount', 1,
		}),
		PlaceObj('RecipeIngredient', {
			'item', "Parts",
			'amount', 1,
		}),
	},
	ResultItems = {
		PlaceObj('RecipeIngredient', {
			'item', "FragGrenade",
			'amount', 60,
		}),
	},
	group = "Explosives",
	id = "stickgrenade_unbox",
	save_in = "Common",
})

PlaceObj('RecipeDef', {
	Difficulty = 3,
	MechanicalRoll = true,
	Ingredients = {
		PlaceObj('RecipeIngredient', {
			'item', "crate_HEGrenade",
			'amount', 1,
		}),
		PlaceObj('RecipeIngredient', {
			'item', "Parts",
			'amount', 1,
		}),
	},
	ResultItems = {
		PlaceObj('RecipeIngredient', {
			'item', "HE_Grenade",
			'amount', 30,
		}),
	},
	group = "Explosives",
	id = "pineapple_unbox",
	save_in = "Common",
})

PlaceObj('RecipeDef', {
	Difficulty = 3,
	MechanicalRoll = true,
	Ingredients = {
		PlaceObj('RecipeIngredient', {
			'item', "crate_CamoLight",
			'amount', 1,
		}),
		PlaceObj('RecipeIngredient', {
			'item', "Parts",
			'amount', 1,
		}),
	},
	ResultItems = {
		PlaceObj('RecipeIngredient', {
			'item', "CamoArmor_Light",
			'amount', 1,
		}),
	},
	group = "Explosives",
	id = "camolight_unbox",
	save_in = "Common",
})

PlaceObj('RecipeDef', {
	Difficulty = 3,
	MechanicalRoll = true,
	Ingredients = {
		PlaceObj('RecipeIngredient', {
			'item', "crate_camomedium",
			'amount', 1,
		}),
		PlaceObj('RecipeIngredient', {
			'item', "Parts",
			'amount', 1,
		}),
	},
	ResultItems = {
		PlaceObj('RecipeIngredient', {
			'item', "CamoArmor_Medium",
			'amount', 1,
		}),
	},
	group = "Explosives",
	id = "camomedium_unbox",
	save_in = "Common",
})

PlaceObj('RecipeDef', {
	Difficulty = 3,
	MechanicalRoll = true,
	Ingredients = {
		PlaceObj('RecipeIngredient', {
			'item', "crate_gasmask",
			'amount', 1,
		}),
		PlaceObj('RecipeIngredient', {
			'item', "Parts",
			'amount', 1,
		}),
	},
	ResultItems = {
		PlaceObj('RecipeIngredient', {
			'item', "GasMask",
			'amount', 1,
		}),
	},
	group = "Explosives",
	id = "gasmask_unbox",
	save_in = "Common",
})

PlaceObj('RecipeDef', {
	Difficulty = 3,
	MechanicalRoll = true,
	Ingredients = {
		PlaceObj('RecipeIngredient', {
			'item', "crate_nightvisiongoggles",
			'amount', 1,
		}),
		PlaceObj('RecipeIngredient', {
			'item', "Parts",
			'amount', 1,
		}),
	},
	ResultItems = {
		PlaceObj('RecipeIngredient', {
			'item', "NightVisionGoggles",
			'amount', 5,
		}),
	},
	group = "Explosives",
	id = "nightvision_unbox",
	save_in = "Common",
})

PlaceObj('RecipeDef', {
	Difficulty = 3,
	MechanicalRoll = true,
	Ingredients = {
		PlaceObj('RecipeIngredient', {
			'item', "crate_KevlarSet",
			'amount', 1,
		}),
		PlaceObj('RecipeIngredient', {
			'item', "Parts",
			'amount', 1,
		}),
	},
	ResultItems = {
		PlaceObj('RecipeIngredient', {
			'item', "KevlarChestplate",
			'amount', 1,
		}),
		PlaceObj('RecipeIngredient', {
			'item', "KevlarHelmet",
			'amount', 1,
		}),
	},
	group = "Explosives",
	id = "kevlarset_unbox",
	save_in = "Common",
})

PlaceObj('RecipeDef', {
	Difficulty = 3,
	MechanicalRoll = true,
	Ingredients = {
		PlaceObj('RecipeIngredient', {
			'item', "crate_HeavySet",
			'amount', 1,
		}),
		PlaceObj('RecipeIngredient', {
			'item', "Parts",
			'amount', 1,
		}),
	},
	ResultItems = {
		PlaceObj('RecipeIngredient', {
			'item', "HeavyArmorChestplate",
			'amount', 1,
		}),
		PlaceObj('RecipeIngredient', {
			'item', "HeavyArmorHelmet",
			'amount', 1,
		}),
	},
	group = "Explosives",
	id = "heavyarmor_unbox",
	save_in = "Common",
})

PlaceObj('RecipeDef', {
	Difficulty = 3,
	MechanicalRoll = true,
	Ingredients = {
		PlaceObj('RecipeIngredient', {
			'item', "crate_44cal",
			'amount', 1,
		}),
		PlaceObj('RecipeIngredient', {
			'item', "Parts",
			'amount', 1,
		}),
	},
	ResultItems = {
		PlaceObj('RecipeIngredient', {
			'item', "_44CAL_Basic",
			'amount', 60,
		}),
		PlaceObj('RecipeIngredient', {
			'item', "Parts",
			'amount', 1,
		}),
	},
	group = "Explosives",
	id = "44cal_unbox",
	save_in = "Common",
})

PlaceObj('RecipeDef', {
	Difficulty = 3,
	MechanicalRoll = true,
	Ingredients = {
		PlaceObj('RecipeIngredient', {
			'item', "crate_12gaugebuckshot",
			'amount', 1,
		}),
		PlaceObj('RecipeIngredient', {
			'item', "Parts",
			'amount', 1,
		}),
	},
	ResultItems = {
		PlaceObj('RecipeIngredient', {
			'item', "_12gauge_Buckshot",
			'amount', 50,
		}),
	},
	group = "Explosives",
	id = "buckshot_unbox",
	save_in = "Common",
})

PlaceObj('RecipeDef', {
	Difficulty = 3,
	MechanicalRoll = true,
	Ingredients = {
		PlaceObj('RecipeIngredient', {
			'item', "crate_50bmg",
			'amount', 1,
		}),
		PlaceObj('RecipeIngredient', {
			'item', "Parts",
			'amount', 1,
		}),
	},
	ResultItems = {
		PlaceObj('RecipeIngredient', {
			'item', "_50BMG_Basic",
			'amount', 150,
		}),
	},
	group = "Explosives",
	id = "50bmg_unbox",
	save_in = "Common",
})

PlaceObj('RecipeDef', {
	Difficulty = 3,
	MechanicalRoll = true,
	Ingredients = {
		PlaceObj('RecipeIngredient', {
			'item', "crate_556",
			'amount', 1,
		}),
		PlaceObj('RecipeIngredient', {
			'item', "Parts",
			'amount', 1,
		}),
	},
	ResultItems = {
		PlaceObj('RecipeIngredient', {
			'item', "_556_Basic",
			'amount', 250,
		}),
	},
	group = "Explosives",
	id = "556_unbox",
	save_in = "Common",
})

PlaceObj('RecipeDef', {
	Difficulty = 3,
	MechanicalRoll = true,
	Ingredients = {
		PlaceObj('RecipeIngredient', {
			'item', "crate_762nato",
			'amount', 1,
		}),
		PlaceObj('RecipeIngredient', {
			'item', "Parts",
			'amount', 1,
		}),
	},
	ResultItems = {
		PlaceObj('RecipeIngredient', {
			'item', "_762NATO_Basic",
			'amount', 200,
		}),
	},
	group = "Explosives",
	id = "762nato_unbox",
	save_in = "Common",
})

PlaceObj('RecipeDef', {
	Difficulty = 3,
	MechanicalRoll = true,
	Ingredients = {
		PlaceObj('RecipeIngredient', {
			'item', "crate_762WP",
			'amount', 1,
		}),
		PlaceObj('RecipeIngredient', {
			'item', "Parts",
			'amount', 1,
		}),
	},
	ResultItems = {
		PlaceObj('RecipeIngredient', {
			'item', "_762WP_Basic",
			'amount', 250,
		}),
	},
	group = "Explosives",
	id = "762wp_unbox",
	save_in = "Common",
})

PlaceObj('RecipeDef', {
	Difficulty = 3,
	MechanicalRoll = true,
	Ingredients = {
		PlaceObj('RecipeIngredient', {
			'item', "crate_9mm",
			'amount', 1,
		}),
		PlaceObj('RecipeIngredient', {
			'item', "Parts",
			'amount', 1,
		}),
	},
	ResultItems = {
		PlaceObj('RecipeIngredient', {
			'item', "_9mm_Basic",
			'amount', 200,
		}),
	},
	group = "Explosives",
	id = "9mm_crate_unbox",
	save_in = "Common",
})

PlaceObj('RecipeDef', {
	Difficulty = 3,
	MechanicalRoll = true,
	Ingredients = {
		PlaceObj('RecipeIngredient', {
			'item', "DiamondBriefcase",
			'amount', 1,
		}),
		PlaceObj('RecipeIngredient', {
			'item', "Knife",
			'amount', 1,
		}),
	},
	ResultItems = {
		PlaceObj('RecipeIngredient', {
			'item', "TinyDiamonds",
			'amount', 15,
		}),
		PlaceObj('RecipeIngredient', {
			'item', "Knife",
			'amount', 1,
		}),
	},
	group = "Explosives",
	id = "diamond_split",
	save_in = "Common",
})

PlaceObj('RecipeDef', {
	Difficulty = 3,
	MechanicalRoll = true,
	Ingredients = {
		PlaceObj('RecipeIngredient', {
			'item', "DiamondBriefcase",
			'amount', 1,
		}),
		PlaceObj('RecipeIngredient', {
			'item', "Knife_Balanced",
			'amount', 1,
		}),
	},
	ResultItems = {
		PlaceObj('RecipeIngredient', {
			'item', "TinyDiamonds",
			'amount', 20,
		}),
		PlaceObj('RecipeIngredient', {
			'item', "Knife_Balanced",
			'amount', 1,
		}),
	},
	group = "Explosives",
	id = "diamond_split_bal",
	save_in = "Common",
})

PlaceObj('RecipeDef', {
	Difficulty = 3,
	MechanicalRoll = true,
	Ingredients = {
		PlaceObj('RecipeIngredient', {
			'item', "DiamondBriefcase",
			'amount', 1,
		}),
		PlaceObj('RecipeIngredient', {
			'item', "Knife_Sharpened",
			'amount', 1,
		}),
	},
	ResultItems = {
		PlaceObj('RecipeIngredient', {
			'item', "TinyDiamonds",
			'amount', 25,
		}),
		PlaceObj('RecipeIngredient', {
			'item', "Knife_Sharpened",
			'amount', 1,
		}),
	},
	group = "Explosives",
	id = "diamond_split_sharp",
	save_in = "Common",
})

PlaceObj('RecipeDef', {
	Difficulty = 3,
	MechanicalRoll = true,
	Ingredients = {
		PlaceObj('RecipeIngredient', {
			'item', "crate_plates",
			'amount', 1,
		}),
		PlaceObj('RecipeIngredient', {
			'item', "Parts",
			'amount', 1,
		}),
	},
	ResultItems = {
		PlaceObj('RecipeIngredient', {
			'item', "Combination_CeramicPlates",
			'amount', 5,
		}),
		PlaceObj('RecipeIngredient', {
			'item', "SkillMag_Strength",
			'amount', 1,
		}),
	},
	group = "Explosives",
	id = "plates_unbox",
	save_in = "Common",
})

PlaceObj('RecipeDef', {
	Difficulty = 3,
	MechanicalRoll = true,
	Ingredients = {
		PlaceObj('RecipeIngredient', {
			'item', "crate_lockpick",
			'amount', 1,
		}),
		PlaceObj('RecipeIngredient', {
			'item', "Parts",
			'amount', 1,
		}),
	},
	ResultItems = {
		PlaceObj('RecipeIngredient', {
			'item', "Lockpick",
			'amount', 1,
		}),
		PlaceObj('RecipeIngredient', {
			'item', "SkillMag_Mechanical",
			'amount', 1,
		}),
	},
	group = "Explosives",
	id = "lockpick_unbox",
	save_in = "Common",
})

PlaceObj('RecipeDef', {
	Difficulty = 3,
	MechanicalRoll = true,
	Ingredients = {
		PlaceObj('RecipeIngredient', {
			'item', "crate_firstaidkit",
			'amount', 1,
		}),
		PlaceObj('RecipeIngredient', {
			'item', "Parts",
			'amount', 1,
		}),
	},
	ResultItems = {
		PlaceObj('RecipeIngredient', {
			'item', "FirstAidKit",
			'amount', 1,
		}),
		PlaceObj('RecipeIngredient', {
			'item', "SkillMag_Health",
			'amount', 1,
		}),
	},
	group = "Explosives",
	id = "firstaidkit_unbox",
	save_in = "Common",
})

PlaceObj('RecipeDef', {
	Difficulty = 3,
	MechanicalRoll = true,
	Ingredients = {
		PlaceObj('RecipeIngredient', {
			'item', "crate_knife",
			'amount', 1,
		}),
		PlaceObj('RecipeIngredient', {
			'item', "Parts",
			'amount', 1,
		}),
	},
	ResultItems = {
		PlaceObj('RecipeIngredient', {
			'item', "Knife_Balanced",
			'amount', 1,
		}),
	},
	group = "Explosives",
	id = "knife_unbox",
	save_in = "Common",
})

PlaceObj('RecipeDef', {
	Difficulty = 3,
	MechanicalRoll = true,
	Ingredients = {
		PlaceObj('RecipeIngredient', {
			'item', "crate_machete",
			'amount', 1,
		}),
		PlaceObj('RecipeIngredient', {
			'item', "Parts",
			'amount', 1,
		}),
	},
	ResultItems = {
		PlaceObj('RecipeIngredient', {
			'item', "Machete",
			'amount', 1,
		}),
	},
	group = "Explosives",
	id = "machete_unbox",
	save_in = "Common",
})